// Code generated by mockery v2.53.3. DO NOT EDIT.

package collector

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockStateWriter is an autogenerated mock type for the StateWriter type
type MockStateWriter struct {
	mock.Mock
}

type MockStateWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateWriter) EXPECT() *MockStateWriter_Expecter {
	return &MockStateWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: ctx, collectorName, name, namespace, path, writer
func (_m *MockStateWriter) Write(ctx context.Context, collectorName string, name string, namespace string, path string, writer func(io.Writer) error) error {
	ret := _m.Called(ctx, collectorName, name, namespace, path, writer)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, func(io.Writer) error) error); ok {
		r0 = rf(ctx, collectorName, name, namespace, path, writer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStateWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockStateWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - collectorName string
//   - name string
//   - namespace string
//   - path string
//   - writer func(io.Writer) error
func (_e *MockStateWriter_Expecter) Write(ctx interface{}, collectorName interface{}, name interface{}, namespace interface{}, path interface{}, writer interface{}) *MockStateWriter_Write_Call {
	return &MockStateWriter_Write_Call{Call: _e.mock.On("Write", ctx, collectorName, name, namespace, path, writer)}
}

func (_c *MockStateWriter_Write_Call) Run(run func(ctx context.Context, collectorName string, name string, namespace string, path string, writer func(io.Writer) error)) *MockStateWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(func(io.Writer) error))
	})
	return _c
}

func (_c *MockStateWriter_Write_Call) Return(_a0 error) *MockStateWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStateWriter_Write_Call) RunAndReturn(run func(context.Context, string, string, string, string, func(io.Writer) error) error) *MockStateWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStateWriter creates a new instance of MockStateWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateWriter {
	mock := &MockStateWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
