// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockCloseStreamFunc is an autogenerated mock type for the CloseStreamFunc type
type MockCloseStreamFunc struct {
	mock.Mock
}

type MockCloseStreamFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloseStreamFunc) EXPECT() *MockCloseStreamFunc_Expecter {
	return &MockCloseStreamFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockCloseStreamFunc) Execute() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCloseStreamFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCloseStreamFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockCloseStreamFunc_Expecter) Execute() *MockCloseStreamFunc_Execute_Call {
	return &MockCloseStreamFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockCloseStreamFunc_Execute_Call) Run(run func()) *MockCloseStreamFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCloseStreamFunc_Execute_Call) Return(_a0 error) *MockCloseStreamFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCloseStreamFunc_Execute_Call) RunAndReturn(run func() error) *MockCloseStreamFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCloseStreamFunc creates a new instance of MockCloseStreamFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloseStreamFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloseStreamFunc {
	mock := &MockCloseStreamFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
