// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockCollectorUnionDataType is an autogenerated mock type for the CollectorUnionDataType type
type MockCollectorUnionDataType struct {
	mock.Mock
}

type MockCollectorUnionDataType_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectorUnionDataType) EXPECT() *MockCollectorUnionDataType_Expecter {
	return &MockCollectorUnionDataType_Expecter{mock: &_m.Mock}
}

// NewMockCollectorUnionDataType creates a new instance of MockCollectorUnionDataType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectorUnionDataType(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectorUnionDataType {
	mock := &MockCollectorUnionDataType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
