// Code generated by mockery v2.53.3. DO NOT EDIT.

package usecase

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "github.com/cloudogu/k8s-support-archive-lib/api/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockSupportArchiveInterface is an autogenerated mock type for the supportArchiveInterface type
type mockSupportArchiveInterface struct {
	mock.Mock
}

type mockSupportArchiveInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSupportArchiveInterface) EXPECT() *mockSupportArchiveInterface_Expecter {
	return &mockSupportArchiveInterface_Expecter{mock: &_m.Mock}
}

// AddFinalizer provides a mock function with given fields: ctx, supportArchive, finalizer
func (_m *mockSupportArchiveInterface) AddFinalizer(ctx context.Context, supportArchive *v1.SupportArchive, finalizer string) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for AddFinalizer")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, string) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive, finalizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, string) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive, finalizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive, string) error); ok {
		r1 = rf(ctx, supportArchive, finalizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_AddFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFinalizer'
type mockSupportArchiveInterface_AddFinalizer_Call struct {
	*mock.Call
}

// AddFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
//   - finalizer string
func (_e *mockSupportArchiveInterface_Expecter) AddFinalizer(ctx interface{}, supportArchive interface{}, finalizer interface{}) *mockSupportArchiveInterface_AddFinalizer_Call {
	return &mockSupportArchiveInterface_AddFinalizer_Call{Call: _e.mock.On("AddFinalizer", ctx, supportArchive, finalizer)}
}

func (_c *mockSupportArchiveInterface_AddFinalizer_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive, finalizer string)) *mockSupportArchiveInterface_AddFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive), args[2].(string))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_AddFinalizer_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_AddFinalizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_AddFinalizer_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive, string) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_AddFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, supportArchive, opts
func (_m *mockSupportArchiveInterface) Create(ctx context.Context, supportArchive *v1.SupportArchive, opts metav1.CreateOptions) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, metav1.CreateOptions) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, metav1.CreateOptions) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, supportArchive, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockSupportArchiveInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
//   - opts metav1.CreateOptions
func (_e *mockSupportArchiveInterface_Expecter) Create(ctx interface{}, supportArchive interface{}, opts interface{}) *mockSupportArchiveInterface_Create_Call {
	return &mockSupportArchiveInterface_Create_Call{Call: _e.mock.On("Create", ctx, supportArchive, opts)}
}

func (_c *mockSupportArchiveInterface_Create_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive, opts metav1.CreateOptions)) *mockSupportArchiveInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_Create_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_Create_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive, metav1.CreateOptions) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockSupportArchiveInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSupportArchiveInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockSupportArchiveInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockSupportArchiveInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockSupportArchiveInterface_Delete_Call {
	return &mockSupportArchiveInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockSupportArchiveInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockSupportArchiveInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_Delete_Call) Return(_a0 error) *mockSupportArchiveInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSupportArchiveInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockSupportArchiveInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *mockSupportArchiveInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSupportArchiveInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type mockSupportArchiveInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *mockSupportArchiveInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *mockSupportArchiveInterface_DeleteCollection_Call {
	return &mockSupportArchiveInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *mockSupportArchiveInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *mockSupportArchiveInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_DeleteCollection_Call) Return(_a0 error) *mockSupportArchiveInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSupportArchiveInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *mockSupportArchiveInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockSupportArchiveInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.SupportArchive, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.SupportArchive); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockSupportArchiveInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockSupportArchiveInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockSupportArchiveInterface_Get_Call {
	return &mockSupportArchiveInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockSupportArchiveInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockSupportArchiveInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_Get_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockSupportArchiveInterface) List(ctx context.Context, opts metav1.ListOptions) (*v1.SupportArchiveList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.SupportArchiveList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*v1.SupportArchiveList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *v1.SupportArchiveList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchiveList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockSupportArchiveInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockSupportArchiveInterface_Expecter) List(ctx interface{}, opts interface{}) *mockSupportArchiveInterface_List_Call {
	return &mockSupportArchiveInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockSupportArchiveInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockSupportArchiveInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_List_Call) Return(_a0 *v1.SupportArchiveList, _a1 error) *mockSupportArchiveInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*v1.SupportArchiveList, error)) *mockSupportArchiveInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *mockSupportArchiveInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*v1.SupportArchive, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*v1.SupportArchive, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *v1.SupportArchive); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockSupportArchiveInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *mockSupportArchiveInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *mockSupportArchiveInterface_Patch_Call {
	return &mockSupportArchiveInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *mockSupportArchiveInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *mockSupportArchiveInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *mockSupportArchiveInterface_Patch_Call) Return(result *v1.SupportArchive, err error) *mockSupportArchiveInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockSupportArchiveInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFinalizer provides a mock function with given fields: ctx, supportArchive, finalizer
func (_m *mockSupportArchiveInterface) RemoveFinalizer(ctx context.Context, supportArchive *v1.SupportArchive, finalizer string) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFinalizer")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, string) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive, finalizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, string) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive, finalizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive, string) error); ok {
		r1 = rf(ctx, supportArchive, finalizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_RemoveFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFinalizer'
type mockSupportArchiveInterface_RemoveFinalizer_Call struct {
	*mock.Call
}

// RemoveFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
//   - finalizer string
func (_e *mockSupportArchiveInterface_Expecter) RemoveFinalizer(ctx interface{}, supportArchive interface{}, finalizer interface{}) *mockSupportArchiveInterface_RemoveFinalizer_Call {
	return &mockSupportArchiveInterface_RemoveFinalizer_Call{Call: _e.mock.On("RemoveFinalizer", ctx, supportArchive, finalizer)}
}

func (_c *mockSupportArchiveInterface_RemoveFinalizer_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive, finalizer string)) *mockSupportArchiveInterface_RemoveFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive), args[2].(string))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_RemoveFinalizer_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_RemoveFinalizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_RemoveFinalizer_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive, string) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_RemoveFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, supportArchive, opts
func (_m *mockSupportArchiveInterface) Update(ctx context.Context, supportArchive *v1.SupportArchive, opts metav1.UpdateOptions) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, supportArchive, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockSupportArchiveInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
//   - opts metav1.UpdateOptions
func (_e *mockSupportArchiveInterface_Expecter) Update(ctx interface{}, supportArchive interface{}, opts interface{}) *mockSupportArchiveInterface_Update_Call {
	return &mockSupportArchiveInterface_Update_Call{Call: _e.mock.On("Update", ctx, supportArchive, opts)}
}

func (_c *mockSupportArchiveInterface_Update_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive, opts metav1.UpdateOptions)) *mockSupportArchiveInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_Update_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_Update_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, supportArchive, opts
func (_m *mockSupportArchiveInterface) UpdateStatus(ctx context.Context, supportArchive *v1.SupportArchive, opts metav1.UpdateOptions) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, supportArchive, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type mockSupportArchiveInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
//   - opts metav1.UpdateOptions
func (_e *mockSupportArchiveInterface_Expecter) UpdateStatus(ctx interface{}, supportArchive interface{}, opts interface{}) *mockSupportArchiveInterface_UpdateStatus_Call {
	return &mockSupportArchiveInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, supportArchive, opts)}
}

func (_c *mockSupportArchiveInterface_UpdateStatus_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive, opts metav1.UpdateOptions)) *mockSupportArchiveInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatus_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive, metav1.UpdateOptions) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusCreated provides a mock function with given fields: ctx, supportArchive
func (_m *mockSupportArchiveInterface) UpdateStatusCreated(ctx context.Context, supportArchive *v1.SupportArchive) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusCreated")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive) error); ok {
		r1 = rf(ctx, supportArchive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_UpdateStatusCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusCreated'
type mockSupportArchiveInterface_UpdateStatusCreated_Call struct {
	*mock.Call
}

// UpdateStatusCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
func (_e *mockSupportArchiveInterface_Expecter) UpdateStatusCreated(ctx interface{}, supportArchive interface{}) *mockSupportArchiveInterface_UpdateStatusCreated_Call {
	return &mockSupportArchiveInterface_UpdateStatusCreated_Call{Call: _e.mock.On("UpdateStatusCreated", ctx, supportArchive)}
}

func (_c *mockSupportArchiveInterface_UpdateStatusCreated_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive)) *mockSupportArchiveInterface_UpdateStatusCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusCreated_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_UpdateStatusCreated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusCreated_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_UpdateStatusCreated_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusCreating provides a mock function with given fields: ctx, supportArchive
func (_m *mockSupportArchiveInterface) UpdateStatusCreating(ctx context.Context, supportArchive *v1.SupportArchive) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusCreating")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive) error); ok {
		r1 = rf(ctx, supportArchive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_UpdateStatusCreating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusCreating'
type mockSupportArchiveInterface_UpdateStatusCreating_Call struct {
	*mock.Call
}

// UpdateStatusCreating is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
func (_e *mockSupportArchiveInterface_Expecter) UpdateStatusCreating(ctx interface{}, supportArchive interface{}) *mockSupportArchiveInterface_UpdateStatusCreating_Call {
	return &mockSupportArchiveInterface_UpdateStatusCreating_Call{Call: _e.mock.On("UpdateStatusCreating", ctx, supportArchive)}
}

func (_c *mockSupportArchiveInterface_UpdateStatusCreating_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive)) *mockSupportArchiveInterface_UpdateStatusCreating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusCreating_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_UpdateStatusCreating_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusCreating_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_UpdateStatusCreating_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusDeleting provides a mock function with given fields: ctx, supportArchive
func (_m *mockSupportArchiveInterface) UpdateStatusDeleting(ctx context.Context, supportArchive *v1.SupportArchive) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusDeleting")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive) error); ok {
		r1 = rf(ctx, supportArchive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_UpdateStatusDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusDeleting'
type mockSupportArchiveInterface_UpdateStatusDeleting_Call struct {
	*mock.Call
}

// UpdateStatusDeleting is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
func (_e *mockSupportArchiveInterface_Expecter) UpdateStatusDeleting(ctx interface{}, supportArchive interface{}) *mockSupportArchiveInterface_UpdateStatusDeleting_Call {
	return &mockSupportArchiveInterface_UpdateStatusDeleting_Call{Call: _e.mock.On("UpdateStatusDeleting", ctx, supportArchive)}
}

func (_c *mockSupportArchiveInterface_UpdateStatusDeleting_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive)) *mockSupportArchiveInterface_UpdateStatusDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusDeleting_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_UpdateStatusDeleting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusDeleting_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_UpdateStatusDeleting_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusFailed provides a mock function with given fields: ctx, supportArchive
func (_m *mockSupportArchiveInterface) UpdateStatusFailed(ctx context.Context, supportArchive *v1.SupportArchive) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, supportArchive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusFailed")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)); ok {
		return rf(ctx, supportArchive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) *v1.SupportArchive); ok {
		r0 = rf(ctx, supportArchive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive) error); ok {
		r1 = rf(ctx, supportArchive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_UpdateStatusFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusFailed'
type mockSupportArchiveInterface_UpdateStatusFailed_Call struct {
	*mock.Call
}

// UpdateStatusFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchive *v1.SupportArchive
func (_e *mockSupportArchiveInterface_Expecter) UpdateStatusFailed(ctx interface{}, supportArchive interface{}) *mockSupportArchiveInterface_UpdateStatusFailed_Call {
	return &mockSupportArchiveInterface_UpdateStatusFailed_Call{Call: _e.mock.On("UpdateStatusFailed", ctx, supportArchive)}
}

func (_c *mockSupportArchiveInterface_UpdateStatusFailed_Call) Run(run func(ctx context.Context, supportArchive *v1.SupportArchive)) *mockSupportArchiveInterface_UpdateStatusFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusFailed_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_UpdateStatusFailed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusFailed_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_UpdateStatusFailed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusWithRetry provides a mock function with given fields: ctx, cr, modifyStatusFn, opts
func (_m *mockSupportArchiveInterface) UpdateStatusWithRetry(ctx context.Context, cr *v1.SupportArchive, modifyStatusFn func(v1.SupportArchiveStatus) v1.SupportArchiveStatus, opts metav1.UpdateOptions) (*v1.SupportArchive, error) {
	ret := _m.Called(ctx, cr, modifyStatusFn, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusWithRetry")
	}

	var r0 *v1.SupportArchive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, func(v1.SupportArchiveStatus) v1.SupportArchiveStatus, metav1.UpdateOptions) (*v1.SupportArchive, error)); ok {
		return rf(ctx, cr, modifyStatusFn, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive, func(v1.SupportArchiveStatus) v1.SupportArchiveStatus, metav1.UpdateOptions) *v1.SupportArchive); ok {
		r0 = rf(ctx, cr, modifyStatusFn, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SupportArchive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive, func(v1.SupportArchiveStatus) v1.SupportArchiveStatus, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, cr, modifyStatusFn, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_UpdateStatusWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusWithRetry'
type mockSupportArchiveInterface_UpdateStatusWithRetry_Call struct {
	*mock.Call
}

// UpdateStatusWithRetry is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *v1.SupportArchive
//   - modifyStatusFn func(v1.SupportArchiveStatus) v1.SupportArchiveStatus
//   - opts metav1.UpdateOptions
func (_e *mockSupportArchiveInterface_Expecter) UpdateStatusWithRetry(ctx interface{}, cr interface{}, modifyStatusFn interface{}, opts interface{}) *mockSupportArchiveInterface_UpdateStatusWithRetry_Call {
	return &mockSupportArchiveInterface_UpdateStatusWithRetry_Call{Call: _e.mock.On("UpdateStatusWithRetry", ctx, cr, modifyStatusFn, opts)}
}

func (_c *mockSupportArchiveInterface_UpdateStatusWithRetry_Call) Run(run func(ctx context.Context, cr *v1.SupportArchive, modifyStatusFn func(v1.SupportArchiveStatus) v1.SupportArchiveStatus, opts metav1.UpdateOptions)) *mockSupportArchiveInterface_UpdateStatusWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive), args[2].(func(v1.SupportArchiveStatus) v1.SupportArchiveStatus), args[3].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusWithRetry_Call) Return(_a0 *v1.SupportArchive, _a1 error) *mockSupportArchiveInterface_UpdateStatusWithRetry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_UpdateStatusWithRetry_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive, func(v1.SupportArchiveStatus) v1.SupportArchiveStatus, metav1.UpdateOptions) (*v1.SupportArchive, error)) *mockSupportArchiveInterface_UpdateStatusWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockSupportArchiveInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockSupportArchiveInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockSupportArchiveInterface_Expecter) Watch(ctx interface{}, opts interface{}) *mockSupportArchiveInterface_Watch_Call {
	return &mockSupportArchiveInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockSupportArchiveInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockSupportArchiveInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockSupportArchiveInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockSupportArchiveInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *mockSupportArchiveInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSupportArchiveInterface creates a new instance of mockSupportArchiveInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSupportArchiveInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSupportArchiveInterface {
	mock := &mockSupportArchiveInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
