// Code generated by mockery v2.53.3. DO NOT EDIT.

package usecase

import (
	context "context"

	domain "github.com/cloudogu/k8s-support-archive-operator/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockSupportArchiveRepository is an autogenerated mock type for the supportArchiveRepository type
type mockSupportArchiveRepository struct {
	mock.Mock
}

type mockSupportArchiveRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSupportArchiveRepository) EXPECT() *mockSupportArchiveRepository_Expecter {
	return &mockSupportArchiveRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, id, streams
func (_m *mockSupportArchiveRepository) Create(ctx context.Context, id domain.SupportArchiveID, streams map[domain.CollectorType]*domain.Stream) (string, error) {
	ret := _m.Called(ctx, id, streams)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SupportArchiveID, map[domain.CollectorType]*domain.Stream) (string, error)); ok {
		return rf(ctx, id, streams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SupportArchiveID, map[domain.CollectorType]*domain.Stream) string); ok {
		r0 = rf(ctx, id, streams)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SupportArchiveID, map[domain.CollectorType]*domain.Stream) error); ok {
		r1 = rf(ctx, id, streams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockSupportArchiveRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SupportArchiveID
//   - streams map[domain.CollectorType]*domain.Stream
func (_e *mockSupportArchiveRepository_Expecter) Create(ctx interface{}, id interface{}, streams interface{}) *mockSupportArchiveRepository_Create_Call {
	return &mockSupportArchiveRepository_Create_Call{Call: _e.mock.On("Create", ctx, id, streams)}
}

func (_c *mockSupportArchiveRepository_Create_Call) Run(run func(ctx context.Context, id domain.SupportArchiveID, streams map[domain.CollectorType]*domain.Stream)) *mockSupportArchiveRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SupportArchiveID), args[2].(map[domain.CollectorType]*domain.Stream))
	})
	return _c
}

func (_c *mockSupportArchiveRepository_Create_Call) Return(url string, err error) *mockSupportArchiveRepository_Create_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *mockSupportArchiveRepository_Create_Call) RunAndReturn(run func(context.Context, domain.SupportArchiveID, map[domain.CollectorType]*domain.Stream) (string, error)) *mockSupportArchiveRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *mockSupportArchiveRepository) Delete(ctx context.Context, id domain.SupportArchiveID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SupportArchiveID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSupportArchiveRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockSupportArchiveRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SupportArchiveID
func (_e *mockSupportArchiveRepository_Expecter) Delete(ctx interface{}, id interface{}) *mockSupportArchiveRepository_Delete_Call {
	return &mockSupportArchiveRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *mockSupportArchiveRepository_Delete_Call) Run(run func(ctx context.Context, id domain.SupportArchiveID)) *mockSupportArchiveRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SupportArchiveID))
	})
	return _c
}

func (_c *mockSupportArchiveRepository_Delete_Call) Return(_a0 error) *mockSupportArchiveRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSupportArchiveRepository_Delete_Call) RunAndReturn(run func(context.Context, domain.SupportArchiveID) error) *mockSupportArchiveRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, id
func (_m *mockSupportArchiveRepository) Exists(ctx context.Context, id domain.SupportArchiveID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SupportArchiveID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SupportArchiveID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SupportArchiveID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSupportArchiveRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockSupportArchiveRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SupportArchiveID
func (_e *mockSupportArchiveRepository_Expecter) Exists(ctx interface{}, id interface{}) *mockSupportArchiveRepository_Exists_Call {
	return &mockSupportArchiveRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *mockSupportArchiveRepository_Exists_Call) Run(run func(ctx context.Context, id domain.SupportArchiveID)) *mockSupportArchiveRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SupportArchiveID))
	})
	return _c
}

func (_c *mockSupportArchiveRepository_Exists_Call) Return(_a0 bool, _a1 error) *mockSupportArchiveRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSupportArchiveRepository_Exists_Call) RunAndReturn(run func(context.Context, domain.SupportArchiveID) (bool, error)) *mockSupportArchiveRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSupportArchiveRepository creates a new instance of mockSupportArchiveRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSupportArchiveRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSupportArchiveRepository {
	mock := &mockSupportArchiveRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
