// Code generated by mockery v2.53.3. DO NOT EDIT.

package v1

import (
	context "context"

	model "github.com/prometheus/common/model"
	mock "github.com/stretchr/testify/mock"

	prometheusv1 "github.com/prometheus/client_golang/api/prometheus/v1"

	time "time"
)

// mockV1API is an autogenerated mock type for the v1API type
type mockV1API struct {
	mock.Mock
}

type mockV1API_Expecter struct {
	mock *mock.Mock
}

func (_m *mockV1API) EXPECT() *mockV1API_Expecter {
	return &mockV1API_Expecter{mock: &_m.Mock}
}

// AlertManagers provides a mock function with given fields: ctx
func (_m *mockV1API) AlertManagers(ctx context.Context) (prometheusv1.AlertManagersResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AlertManagers")
	}

	var r0 prometheusv1.AlertManagersResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.AlertManagersResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.AlertManagersResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.AlertManagersResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_AlertManagers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlertManagers'
type mockV1API_AlertManagers_Call struct {
	*mock.Call
}

// AlertManagers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) AlertManagers(ctx interface{}) *mockV1API_AlertManagers_Call {
	return &mockV1API_AlertManagers_Call{Call: _e.mock.On("AlertManagers", ctx)}
}

func (_c *mockV1API_AlertManagers_Call) Run(run func(ctx context.Context)) *mockV1API_AlertManagers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_AlertManagers_Call) Return(_a0 prometheusv1.AlertManagersResult, _a1 error) *mockV1API_AlertManagers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_AlertManagers_Call) RunAndReturn(run func(context.Context) (prometheusv1.AlertManagersResult, error)) *mockV1API_AlertManagers_Call {
	_c.Call.Return(run)
	return _c
}

// Alerts provides a mock function with given fields: ctx
func (_m *mockV1API) Alerts(ctx context.Context) (prometheusv1.AlertsResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Alerts")
	}

	var r0 prometheusv1.AlertsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.AlertsResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.AlertsResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.AlertsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Alerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alerts'
type mockV1API_Alerts_Call struct {
	*mock.Call
}

// Alerts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) Alerts(ctx interface{}) *mockV1API_Alerts_Call {
	return &mockV1API_Alerts_Call{Call: _e.mock.On("Alerts", ctx)}
}

func (_c *mockV1API_Alerts_Call) Run(run func(ctx context.Context)) *mockV1API_Alerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_Alerts_Call) Return(_a0 prometheusv1.AlertsResult, _a1 error) *mockV1API_Alerts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Alerts_Call) RunAndReturn(run func(context.Context) (prometheusv1.AlertsResult, error)) *mockV1API_Alerts_Call {
	_c.Call.Return(run)
	return _c
}

// Buildinfo provides a mock function with given fields: ctx
func (_m *mockV1API) Buildinfo(ctx context.Context) (prometheusv1.BuildinfoResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Buildinfo")
	}

	var r0 prometheusv1.BuildinfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.BuildinfoResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.BuildinfoResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.BuildinfoResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Buildinfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Buildinfo'
type mockV1API_Buildinfo_Call struct {
	*mock.Call
}

// Buildinfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) Buildinfo(ctx interface{}) *mockV1API_Buildinfo_Call {
	return &mockV1API_Buildinfo_Call{Call: _e.mock.On("Buildinfo", ctx)}
}

func (_c *mockV1API_Buildinfo_Call) Run(run func(ctx context.Context)) *mockV1API_Buildinfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_Buildinfo_Call) Return(_a0 prometheusv1.BuildinfoResult, _a1 error) *mockV1API_Buildinfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Buildinfo_Call) RunAndReturn(run func(context.Context) (prometheusv1.BuildinfoResult, error)) *mockV1API_Buildinfo_Call {
	_c.Call.Return(run)
	return _c
}

// CleanTombstones provides a mock function with given fields: ctx
func (_m *mockV1API) CleanTombstones(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanTombstones")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockV1API_CleanTombstones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanTombstones'
type mockV1API_CleanTombstones_Call struct {
	*mock.Call
}

// CleanTombstones is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) CleanTombstones(ctx interface{}) *mockV1API_CleanTombstones_Call {
	return &mockV1API_CleanTombstones_Call{Call: _e.mock.On("CleanTombstones", ctx)}
}

func (_c *mockV1API_CleanTombstones_Call) Run(run func(ctx context.Context)) *mockV1API_CleanTombstones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_CleanTombstones_Call) Return(_a0 error) *mockV1API_CleanTombstones_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockV1API_CleanTombstones_Call) RunAndReturn(run func(context.Context) error) *mockV1API_CleanTombstones_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function with given fields: ctx
func (_m *mockV1API) Config(ctx context.Context) (prometheusv1.ConfigResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 prometheusv1.ConfigResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.ConfigResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.ConfigResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.ConfigResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type mockV1API_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) Config(ctx interface{}) *mockV1API_Config_Call {
	return &mockV1API_Config_Call{Call: _e.mock.On("Config", ctx)}
}

func (_c *mockV1API_Config_Call) Run(run func(ctx context.Context)) *mockV1API_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_Config_Call) Return(_a0 prometheusv1.ConfigResult, _a1 error) *mockV1API_Config_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Config_Call) RunAndReturn(run func(context.Context) (prometheusv1.ConfigResult, error)) *mockV1API_Config_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSeries provides a mock function with given fields: ctx, matches, startTime, endTime
func (_m *mockV1API) DeleteSeries(ctx context.Context, matches []string, startTime time.Time, endTime time.Time) error {
	ret := _m.Called(ctx, matches, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSeries")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, matches, startTime, endTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockV1API_DeleteSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSeries'
type mockV1API_DeleteSeries_Call struct {
	*mock.Call
}

// DeleteSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
func (_e *mockV1API_Expecter) DeleteSeries(ctx interface{}, matches interface{}, startTime interface{}, endTime interface{}) *mockV1API_DeleteSeries_Call {
	return &mockV1API_DeleteSeries_Call{Call: _e.mock.On("DeleteSeries", ctx, matches, startTime, endTime)}
}

func (_c *mockV1API_DeleteSeries_Call) Run(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time)) *mockV1API_DeleteSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *mockV1API_DeleteSeries_Call) Return(_a0 error) *mockV1API_DeleteSeries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockV1API_DeleteSeries_Call) RunAndReturn(run func(context.Context, []string, time.Time, time.Time) error) *mockV1API_DeleteSeries_Call {
	_c.Call.Return(run)
	return _c
}

// Flags provides a mock function with given fields: ctx
func (_m *mockV1API) Flags(ctx context.Context) (prometheusv1.FlagsResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Flags")
	}

	var r0 prometheusv1.FlagsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.FlagsResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.FlagsResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prometheusv1.FlagsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Flags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flags'
type mockV1API_Flags_Call struct {
	*mock.Call
}

// Flags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) Flags(ctx interface{}) *mockV1API_Flags_Call {
	return &mockV1API_Flags_Call{Call: _e.mock.On("Flags", ctx)}
}

func (_c *mockV1API_Flags_Call) Run(run func(ctx context.Context)) *mockV1API_Flags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_Flags_Call) Return(_a0 prometheusv1.FlagsResult, _a1 error) *mockV1API_Flags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Flags_Call) RunAndReturn(run func(context.Context) (prometheusv1.FlagsResult, error)) *mockV1API_Flags_Call {
	_c.Call.Return(run)
	return _c
}

// LabelNames provides a mock function with given fields: ctx, matches, startTime, endTime, opts
func (_m *mockV1API) LabelNames(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...prometheusv1.Option) ([]string, prometheusv1.Warnings, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, matches, startTime, endTime)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabelNames")
	}

	var r0 []string
	var r1 prometheusv1.Warnings
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) ([]string, prometheusv1.Warnings, error)); ok {
		return rf(ctx, matches, startTime, endTime, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) []string); ok {
		r0 = rf(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) prometheusv1.Warnings); ok {
		r1 = rf(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(prometheusv1.Warnings)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) error); ok {
		r2 = rf(ctx, matches, startTime, endTime, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockV1API_LabelNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LabelNames'
type mockV1API_LabelNames_Call struct {
	*mock.Call
}

// LabelNames is a helper method to define mock.On call
//   - ctx context.Context
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
//   - opts ...prometheusv1.Option
func (_e *mockV1API_Expecter) LabelNames(ctx interface{}, matches interface{}, startTime interface{}, endTime interface{}, opts ...interface{}) *mockV1API_LabelNames_Call {
	return &mockV1API_LabelNames_Call{Call: _e.mock.On("LabelNames",
		append([]interface{}{ctx, matches, startTime, endTime}, opts...)...)}
}

func (_c *mockV1API_LabelNames_Call) Run(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...prometheusv1.Option)) *mockV1API_LabelNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]prometheusv1.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(prometheusv1.Option)
			}
		}
		run(args[0].(context.Context), args[1].([]string), args[2].(time.Time), args[3].(time.Time), variadicArgs...)
	})
	return _c
}

func (_c *mockV1API_LabelNames_Call) Return(_a0 []string, _a1 prometheusv1.Warnings, _a2 error) *mockV1API_LabelNames_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockV1API_LabelNames_Call) RunAndReturn(run func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) ([]string, prometheusv1.Warnings, error)) *mockV1API_LabelNames_Call {
	_c.Call.Return(run)
	return _c
}

// LabelValues provides a mock function with given fields: ctx, label, matches, startTime, endTime, opts
func (_m *mockV1API) LabelValues(ctx context.Context, label string, matches []string, startTime time.Time, endTime time.Time, opts ...prometheusv1.Option) (model.LabelValues, prometheusv1.Warnings, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, label, matches, startTime, endTime)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LabelValues")
	}

	var r0 model.LabelValues
	var r1 prometheusv1.Warnings
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, time.Time, time.Time, ...prometheusv1.Option) (model.LabelValues, prometheusv1.Warnings, error)); ok {
		return rf(ctx, label, matches, startTime, endTime, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, time.Time, time.Time, ...prometheusv1.Option) model.LabelValues); ok {
		r0 = rf(ctx, label, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.LabelValues)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, time.Time, time.Time, ...prometheusv1.Option) prometheusv1.Warnings); ok {
		r1 = rf(ctx, label, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(prometheusv1.Warnings)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []string, time.Time, time.Time, ...prometheusv1.Option) error); ok {
		r2 = rf(ctx, label, matches, startTime, endTime, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockV1API_LabelValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LabelValues'
type mockV1API_LabelValues_Call struct {
	*mock.Call
}

// LabelValues is a helper method to define mock.On call
//   - ctx context.Context
//   - label string
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
//   - opts ...prometheusv1.Option
func (_e *mockV1API_Expecter) LabelValues(ctx interface{}, label interface{}, matches interface{}, startTime interface{}, endTime interface{}, opts ...interface{}) *mockV1API_LabelValues_Call {
	return &mockV1API_LabelValues_Call{Call: _e.mock.On("LabelValues",
		append([]interface{}{ctx, label, matches, startTime, endTime}, opts...)...)}
}

func (_c *mockV1API_LabelValues_Call) Run(run func(ctx context.Context, label string, matches []string, startTime time.Time, endTime time.Time, opts ...prometheusv1.Option)) *mockV1API_LabelValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]prometheusv1.Option, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(prometheusv1.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(time.Time), args[4].(time.Time), variadicArgs...)
	})
	return _c
}

func (_c *mockV1API_LabelValues_Call) Return(_a0 model.LabelValues, _a1 prometheusv1.Warnings, _a2 error) *mockV1API_LabelValues_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockV1API_LabelValues_Call) RunAndReturn(run func(context.Context, string, []string, time.Time, time.Time, ...prometheusv1.Option) (model.LabelValues, prometheusv1.Warnings, error)) *mockV1API_LabelValues_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with given fields: ctx, metric, limit
func (_m *mockV1API) Metadata(ctx context.Context, metric string, limit string) (map[string][]prometheusv1.Metadata, error) {
	ret := _m.Called(ctx, metric, limit)

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 map[string][]prometheusv1.Metadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string][]prometheusv1.Metadata, error)); ok {
		return rf(ctx, metric, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string][]prometheusv1.Metadata); ok {
		r0 = rf(ctx, metric, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]prometheusv1.Metadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, metric, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type mockV1API_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
//   - ctx context.Context
//   - metric string
//   - limit string
func (_e *mockV1API_Expecter) Metadata(ctx interface{}, metric interface{}, limit interface{}) *mockV1API_Metadata_Call {
	return &mockV1API_Metadata_Call{Call: _e.mock.On("Metadata", ctx, metric, limit)}
}

func (_c *mockV1API_Metadata_Call) Run(run func(ctx context.Context, metric string, limit string)) *mockV1API_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockV1API_Metadata_Call) Return(_a0 map[string][]prometheusv1.Metadata, _a1 error) *mockV1API_Metadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Metadata_Call) RunAndReturn(run func(context.Context, string, string) (map[string][]prometheusv1.Metadata, error)) *mockV1API_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, query, ts, opts
func (_m *mockV1API) Query(ctx context.Context, query string, ts time.Time, opts ...prometheusv1.Option) (model.Value, prometheusv1.Warnings, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query, ts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 model.Value
	var r1 prometheusv1.Warnings
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, ...prometheusv1.Option) (model.Value, prometheusv1.Warnings, error)); ok {
		return rf(ctx, query, ts, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, ...prometheusv1.Option) model.Value); ok {
		r0 = rf(ctx, query, ts, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Value)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, ...prometheusv1.Option) prometheusv1.Warnings); ok {
		r1 = rf(ctx, query, ts, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(prometheusv1.Warnings)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, time.Time, ...prometheusv1.Option) error); ok {
		r2 = rf(ctx, query, ts, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockV1API_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type mockV1API_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - ts time.Time
//   - opts ...prometheusv1.Option
func (_e *mockV1API_Expecter) Query(ctx interface{}, query interface{}, ts interface{}, opts ...interface{}) *mockV1API_Query_Call {
	return &mockV1API_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query, ts}, opts...)...)}
}

func (_c *mockV1API_Query_Call) Run(run func(ctx context.Context, query string, ts time.Time, opts ...prometheusv1.Option)) *mockV1API_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]prometheusv1.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(prometheusv1.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), variadicArgs...)
	})
	return _c
}

func (_c *mockV1API_Query_Call) Return(_a0 model.Value, _a1 prometheusv1.Warnings, _a2 error) *mockV1API_Query_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockV1API_Query_Call) RunAndReturn(run func(context.Context, string, time.Time, ...prometheusv1.Option) (model.Value, prometheusv1.Warnings, error)) *mockV1API_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryExemplars provides a mock function with given fields: ctx, query, startTime, endTime
func (_m *mockV1API) QueryExemplars(ctx context.Context, query string, startTime time.Time, endTime time.Time) ([]prometheusv1.ExemplarQueryResult, error) {
	ret := _m.Called(ctx, query, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for QueryExemplars")
	}

	var r0 []prometheusv1.ExemplarQueryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]prometheusv1.ExemplarQueryResult, error)); ok {
		return rf(ctx, query, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []prometheusv1.ExemplarQueryResult); ok {
		r0 = rf(ctx, query, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]prometheusv1.ExemplarQueryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, query, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_QueryExemplars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryExemplars'
type mockV1API_QueryExemplars_Call struct {
	*mock.Call
}

// QueryExemplars is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - startTime time.Time
//   - endTime time.Time
func (_e *mockV1API_Expecter) QueryExemplars(ctx interface{}, query interface{}, startTime interface{}, endTime interface{}) *mockV1API_QueryExemplars_Call {
	return &mockV1API_QueryExemplars_Call{Call: _e.mock.On("QueryExemplars", ctx, query, startTime, endTime)}
}

func (_c *mockV1API_QueryExemplars_Call) Run(run func(ctx context.Context, query string, startTime time.Time, endTime time.Time)) *mockV1API_QueryExemplars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *mockV1API_QueryExemplars_Call) Return(_a0 []prometheusv1.ExemplarQueryResult, _a1 error) *mockV1API_QueryExemplars_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_QueryExemplars_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]prometheusv1.ExemplarQueryResult, error)) *mockV1API_QueryExemplars_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRange provides a mock function with given fields: ctx, query, r, opts
func (_m *mockV1API) QueryRange(ctx context.Context, query string, r prometheusv1.Range, opts ...prometheusv1.Option) (model.Value, prometheusv1.Warnings, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query, r)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRange")
	}

	var r0 model.Value
	var r1 prometheusv1.Warnings
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, prometheusv1.Range, ...prometheusv1.Option) (model.Value, prometheusv1.Warnings, error)); ok {
		return rf(ctx, query, r, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, prometheusv1.Range, ...prometheusv1.Option) model.Value); ok {
		r0 = rf(ctx, query, r, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Value)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, prometheusv1.Range, ...prometheusv1.Option) prometheusv1.Warnings); ok {
		r1 = rf(ctx, query, r, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(prometheusv1.Warnings)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, prometheusv1.Range, ...prometheusv1.Option) error); ok {
		r2 = rf(ctx, query, r, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockV1API_QueryRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRange'
type mockV1API_QueryRange_Call struct {
	*mock.Call
}

// QueryRange is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - r prometheusv1.Range
//   - opts ...prometheusv1.Option
func (_e *mockV1API_Expecter) QueryRange(ctx interface{}, query interface{}, r interface{}, opts ...interface{}) *mockV1API_QueryRange_Call {
	return &mockV1API_QueryRange_Call{Call: _e.mock.On("QueryRange",
		append([]interface{}{ctx, query, r}, opts...)...)}
}

func (_c *mockV1API_QueryRange_Call) Run(run func(ctx context.Context, query string, r prometheusv1.Range, opts ...prometheusv1.Option)) *mockV1API_QueryRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]prometheusv1.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(prometheusv1.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(prometheusv1.Range), variadicArgs...)
	})
	return _c
}

func (_c *mockV1API_QueryRange_Call) Return(_a0 model.Value, _a1 prometheusv1.Warnings, _a2 error) *mockV1API_QueryRange_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockV1API_QueryRange_Call) RunAndReturn(run func(context.Context, string, prometheusv1.Range, ...prometheusv1.Option) (model.Value, prometheusv1.Warnings, error)) *mockV1API_QueryRange_Call {
	_c.Call.Return(run)
	return _c
}

// Rules provides a mock function with given fields: ctx
func (_m *mockV1API) Rules(ctx context.Context) (prometheusv1.RulesResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rules")
	}

	var r0 prometheusv1.RulesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.RulesResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.RulesResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.RulesResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Rules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rules'
type mockV1API_Rules_Call struct {
	*mock.Call
}

// Rules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) Rules(ctx interface{}) *mockV1API_Rules_Call {
	return &mockV1API_Rules_Call{Call: _e.mock.On("Rules", ctx)}
}

func (_c *mockV1API_Rules_Call) Run(run func(ctx context.Context)) *mockV1API_Rules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_Rules_Call) Return(_a0 prometheusv1.RulesResult, _a1 error) *mockV1API_Rules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Rules_Call) RunAndReturn(run func(context.Context) (prometheusv1.RulesResult, error)) *mockV1API_Rules_Call {
	_c.Call.Return(run)
	return _c
}

// Runtimeinfo provides a mock function with given fields: ctx
func (_m *mockV1API) Runtimeinfo(ctx context.Context) (prometheusv1.RuntimeinfoResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Runtimeinfo")
	}

	var r0 prometheusv1.RuntimeinfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.RuntimeinfoResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.RuntimeinfoResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.RuntimeinfoResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Runtimeinfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Runtimeinfo'
type mockV1API_Runtimeinfo_Call struct {
	*mock.Call
}

// Runtimeinfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) Runtimeinfo(ctx interface{}) *mockV1API_Runtimeinfo_Call {
	return &mockV1API_Runtimeinfo_Call{Call: _e.mock.On("Runtimeinfo", ctx)}
}

func (_c *mockV1API_Runtimeinfo_Call) Run(run func(ctx context.Context)) *mockV1API_Runtimeinfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_Runtimeinfo_Call) Return(_a0 prometheusv1.RuntimeinfoResult, _a1 error) *mockV1API_Runtimeinfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Runtimeinfo_Call) RunAndReturn(run func(context.Context) (prometheusv1.RuntimeinfoResult, error)) *mockV1API_Runtimeinfo_Call {
	_c.Call.Return(run)
	return _c
}

// Series provides a mock function with given fields: ctx, matches, startTime, endTime, opts
func (_m *mockV1API) Series(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...prometheusv1.Option) ([]model.LabelSet, prometheusv1.Warnings, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, matches, startTime, endTime)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Series")
	}

	var r0 []model.LabelSet
	var r1 prometheusv1.Warnings
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) ([]model.LabelSet, prometheusv1.Warnings, error)); ok {
		return rf(ctx, matches, startTime, endTime, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) []model.LabelSet); ok {
		r0 = rf(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LabelSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) prometheusv1.Warnings); ok {
		r1 = rf(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(prometheusv1.Warnings)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) error); ok {
		r2 = rf(ctx, matches, startTime, endTime, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockV1API_Series_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Series'
type mockV1API_Series_Call struct {
	*mock.Call
}

// Series is a helper method to define mock.On call
//   - ctx context.Context
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
//   - opts ...prometheusv1.Option
func (_e *mockV1API_Expecter) Series(ctx interface{}, matches interface{}, startTime interface{}, endTime interface{}, opts ...interface{}) *mockV1API_Series_Call {
	return &mockV1API_Series_Call{Call: _e.mock.On("Series",
		append([]interface{}{ctx, matches, startTime, endTime}, opts...)...)}
}

func (_c *mockV1API_Series_Call) Run(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...prometheusv1.Option)) *mockV1API_Series_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]prometheusv1.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(prometheusv1.Option)
			}
		}
		run(args[0].(context.Context), args[1].([]string), args[2].(time.Time), args[3].(time.Time), variadicArgs...)
	})
	return _c
}

func (_c *mockV1API_Series_Call) Return(_a0 []model.LabelSet, _a1 prometheusv1.Warnings, _a2 error) *mockV1API_Series_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockV1API_Series_Call) RunAndReturn(run func(context.Context, []string, time.Time, time.Time, ...prometheusv1.Option) ([]model.LabelSet, prometheusv1.Warnings, error)) *mockV1API_Series_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function with given fields: ctx, skipHead
func (_m *mockV1API) Snapshot(ctx context.Context, skipHead bool) (prometheusv1.SnapshotResult, error) {
	ret := _m.Called(ctx, skipHead)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 prometheusv1.SnapshotResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) (prometheusv1.SnapshotResult, error)); ok {
		return rf(ctx, skipHead)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) prometheusv1.SnapshotResult); ok {
		r0 = rf(ctx, skipHead)
	} else {
		r0 = ret.Get(0).(prometheusv1.SnapshotResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, skipHead)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type mockV1API_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - skipHead bool
func (_e *mockV1API_Expecter) Snapshot(ctx interface{}, skipHead interface{}) *mockV1API_Snapshot_Call {
	return &mockV1API_Snapshot_Call{Call: _e.mock.On("Snapshot", ctx, skipHead)}
}

func (_c *mockV1API_Snapshot_Call) Run(run func(ctx context.Context, skipHead bool)) *mockV1API_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *mockV1API_Snapshot_Call) Return(_a0 prometheusv1.SnapshotResult, _a1 error) *mockV1API_Snapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Snapshot_Call) RunAndReturn(run func(context.Context, bool) (prometheusv1.SnapshotResult, error)) *mockV1API_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// TSDB provides a mock function with given fields: ctx, opts
func (_m *mockV1API) TSDB(ctx context.Context, opts ...prometheusv1.Option) (prometheusv1.TSDBResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TSDB")
	}

	var r0 prometheusv1.TSDBResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...prometheusv1.Option) (prometheusv1.TSDBResult, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...prometheusv1.Option) prometheusv1.TSDBResult); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Get(0).(prometheusv1.TSDBResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...prometheusv1.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_TSDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TSDB'
type mockV1API_TSDB_Call struct {
	*mock.Call
}

// TSDB is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...prometheusv1.Option
func (_e *mockV1API_Expecter) TSDB(ctx interface{}, opts ...interface{}) *mockV1API_TSDB_Call {
	return &mockV1API_TSDB_Call{Call: _e.mock.On("TSDB",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *mockV1API_TSDB_Call) Run(run func(ctx context.Context, opts ...prometheusv1.Option)) *mockV1API_TSDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]prometheusv1.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(prometheusv1.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *mockV1API_TSDB_Call) Return(_a0 prometheusv1.TSDBResult, _a1 error) *mockV1API_TSDB_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_TSDB_Call) RunAndReturn(run func(context.Context, ...prometheusv1.Option) (prometheusv1.TSDBResult, error)) *mockV1API_TSDB_Call {
	_c.Call.Return(run)
	return _c
}

// Targets provides a mock function with given fields: ctx
func (_m *mockV1API) Targets(ctx context.Context) (prometheusv1.TargetsResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Targets")
	}

	var r0 prometheusv1.TargetsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.TargetsResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.TargetsResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.TargetsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_Targets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Targets'
type mockV1API_Targets_Call struct {
	*mock.Call
}

// Targets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) Targets(ctx interface{}) *mockV1API_Targets_Call {
	return &mockV1API_Targets_Call{Call: _e.mock.On("Targets", ctx)}
}

func (_c *mockV1API_Targets_Call) Run(run func(ctx context.Context)) *mockV1API_Targets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_Targets_Call) Return(_a0 prometheusv1.TargetsResult, _a1 error) *mockV1API_Targets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_Targets_Call) RunAndReturn(run func(context.Context) (prometheusv1.TargetsResult, error)) *mockV1API_Targets_Call {
	_c.Call.Return(run)
	return _c
}

// TargetsMetadata provides a mock function with given fields: ctx, matchTarget, metric, limit
func (_m *mockV1API) TargetsMetadata(ctx context.Context, matchTarget string, metric string, limit string) ([]prometheusv1.MetricMetadata, error) {
	ret := _m.Called(ctx, matchTarget, metric, limit)

	if len(ret) == 0 {
		panic("no return value specified for TargetsMetadata")
	}

	var r0 []prometheusv1.MetricMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]prometheusv1.MetricMetadata, error)); ok {
		return rf(ctx, matchTarget, metric, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []prometheusv1.MetricMetadata); ok {
		r0 = rf(ctx, matchTarget, metric, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]prometheusv1.MetricMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, matchTarget, metric, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_TargetsMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetsMetadata'
type mockV1API_TargetsMetadata_Call struct {
	*mock.Call
}

// TargetsMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - matchTarget string
//   - metric string
//   - limit string
func (_e *mockV1API_Expecter) TargetsMetadata(ctx interface{}, matchTarget interface{}, metric interface{}, limit interface{}) *mockV1API_TargetsMetadata_Call {
	return &mockV1API_TargetsMetadata_Call{Call: _e.mock.On("TargetsMetadata", ctx, matchTarget, metric, limit)}
}

func (_c *mockV1API_TargetsMetadata_Call) Run(run func(ctx context.Context, matchTarget string, metric string, limit string)) *mockV1API_TargetsMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *mockV1API_TargetsMetadata_Call) Return(_a0 []prometheusv1.MetricMetadata, _a1 error) *mockV1API_TargetsMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_TargetsMetadata_Call) RunAndReturn(run func(context.Context, string, string, string) ([]prometheusv1.MetricMetadata, error)) *mockV1API_TargetsMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// WalReplay provides a mock function with given fields: ctx
func (_m *mockV1API) WalReplay(ctx context.Context) (prometheusv1.WalReplayStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WalReplay")
	}

	var r0 prometheusv1.WalReplayStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (prometheusv1.WalReplayStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) prometheusv1.WalReplayStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(prometheusv1.WalReplayStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockV1API_WalReplay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalReplay'
type mockV1API_WalReplay_Call struct {
	*mock.Call
}

// WalReplay is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockV1API_Expecter) WalReplay(ctx interface{}) *mockV1API_WalReplay_Call {
	return &mockV1API_WalReplay_Call{Call: _e.mock.On("WalReplay", ctx)}
}

func (_c *mockV1API_WalReplay_Call) Run(run func(ctx context.Context)) *mockV1API_WalReplay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockV1API_WalReplay_Call) Return(_a0 prometheusv1.WalReplayStatus, _a1 error) *mockV1API_WalReplay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockV1API_WalReplay_Call) RunAndReturn(run func(context.Context) (prometheusv1.WalReplayStatus, error)) *mockV1API_WalReplay_Call {
	_c.Call.Return(run)
	return _c
}

// newMockV1API creates a new instance of mockV1API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockV1API(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockV1API {
	mock := &mockV1API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
