// Code generated by mockery v2.53.3. DO NOT EDIT.

package reconciler

import (
	context "context"

	v1 "github.com/cloudogu/k8s-support-archive-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockArchiveHandler is an autogenerated mock type for the archiveHandler type
type mockArchiveHandler struct {
	mock.Mock
}

type mockArchiveHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockArchiveHandler) EXPECT() *mockArchiveHandler_Expecter {
	return &mockArchiveHandler_Expecter{mock: &_m.Mock}
}

// HandleArchiveRequest provides a mock function with given fields: ctx, cr
func (_m *mockArchiveHandler) HandleArchiveRequest(ctx context.Context, cr *v1.SupportArchive) (bool, error) {
	ret := _m.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for HandleArchiveRequest")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) (bool, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SupportArchive) bool); ok {
		r0 = rf(ctx, cr)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SupportArchive) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockArchiveHandler_HandleArchiveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleArchiveRequest'
type mockArchiveHandler_HandleArchiveRequest_Call struct {
	*mock.Call
}

// HandleArchiveRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *v1.SupportArchive
func (_e *mockArchiveHandler_Expecter) HandleArchiveRequest(ctx interface{}, cr interface{}) *mockArchiveHandler_HandleArchiveRequest_Call {
	return &mockArchiveHandler_HandleArchiveRequest_Call{Call: _e.mock.On("HandleArchiveRequest", ctx, cr)}
}

func (_c *mockArchiveHandler_HandleArchiveRequest_Call) Run(run func(ctx context.Context, cr *v1.SupportArchive)) *mockArchiveHandler_HandleArchiveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.SupportArchive))
	})
	return _c
}

func (_c *mockArchiveHandler_HandleArchiveRequest_Call) Return(requeue bool, err error) *mockArchiveHandler_HandleArchiveRequest_Call {
	_c.Call.Return(requeue, err)
	return _c
}

func (_c *mockArchiveHandler_HandleArchiveRequest_Call) RunAndReturn(run func(context.Context, *v1.SupportArchive) (bool, error)) *mockArchiveHandler_HandleArchiveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// newMockArchiveHandler creates a new instance of mockArchiveHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockArchiveHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockArchiveHandler {
	mock := &mockArchiveHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
