// Code generated by mockery v2.53.3. DO NOT EDIT.

package reconciler

import (
	apiserverinternalv1alpha1 "k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1"
	appsv1 "k8s.io/client-go/kubernetes/typed/apps/v1"

	appsv1beta1 "k8s.io/client-go/kubernetes/typed/apps/v1beta1"

	authenticationv1 "k8s.io/client-go/kubernetes/typed/authentication/v1"

	authenticationv1alpha1 "k8s.io/client-go/kubernetes/typed/authentication/v1alpha1"

	authenticationv1beta1 "k8s.io/client-go/kubernetes/typed/authentication/v1beta1"

	authorizationv1 "k8s.io/client-go/kubernetes/typed/authorization/v1"

	authorizationv1beta1 "k8s.io/client-go/kubernetes/typed/authorization/v1beta1"

	autoscalingv1 "k8s.io/client-go/kubernetes/typed/autoscaling/v1"

	batchv1 "k8s.io/client-go/kubernetes/typed/batch/v1"

	batchv1beta1 "k8s.io/client-go/kubernetes/typed/batch/v1beta1"

	certificatesv1 "k8s.io/client-go/kubernetes/typed/certificates/v1"

	certificatesv1alpha1 "k8s.io/client-go/kubernetes/typed/certificates/v1alpha1"

	certificatesv1beta1 "k8s.io/client-go/kubernetes/typed/certificates/v1beta1"

	clientv1 "github.com/cloudogu/k8s-support-archive-lib/client/v1"

	coordinationv1 "k8s.io/client-go/kubernetes/typed/coordination/v1"

	coordinationv1beta1 "k8s.io/client-go/kubernetes/typed/coordination/v1beta1"

	corev1 "k8s.io/client-go/kubernetes/typed/core/v1"

	discovery "k8s.io/client-go/discovery"

	discoveryv1 "k8s.io/client-go/kubernetes/typed/discovery/v1"

	discoveryv1beta1 "k8s.io/client-go/kubernetes/typed/discovery/v1beta1"

	eventsv1 "k8s.io/client-go/kubernetes/typed/events/v1"

	eventsv1beta1 "k8s.io/client-go/kubernetes/typed/events/v1beta1"

	extensionsv1beta1 "k8s.io/client-go/kubernetes/typed/extensions/v1beta1"

	flowcontrolv1 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1"

	flowcontrolv1beta1 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta1"

	flowcontrolv1beta2 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta2"

	mock "github.com/stretchr/testify/mock"

	networkingv1 "k8s.io/client-go/kubernetes/typed/networking/v1"

	networkingv1alpha1 "k8s.io/client-go/kubernetes/typed/networking/v1alpha1"

	networkingv1beta1 "k8s.io/client-go/kubernetes/typed/networking/v1beta1"

	nodev1 "k8s.io/client-go/kubernetes/typed/node/v1"

	nodev1alpha1 "k8s.io/client-go/kubernetes/typed/node/v1alpha1"

	nodev1beta1 "k8s.io/client-go/kubernetes/typed/node/v1beta1"

	policyv1 "k8s.io/client-go/kubernetes/typed/policy/v1"

	policyv1beta1 "k8s.io/client-go/kubernetes/typed/policy/v1beta1"

	rbacv1 "k8s.io/client-go/kubernetes/typed/rbac/v1"

	rbacv1alpha1 "k8s.io/client-go/kubernetes/typed/rbac/v1alpha1"

	rbacv1beta1 "k8s.io/client-go/kubernetes/typed/rbac/v1beta1"

	resourcev1beta1 "k8s.io/client-go/kubernetes/typed/resource/v1beta1"

	schedulingv1 "k8s.io/client-go/kubernetes/typed/scheduling/v1"

	schedulingv1alpha1 "k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1"

	schedulingv1beta1 "k8s.io/client-go/kubernetes/typed/scheduling/v1beta1"

	storagemigrationv1alpha1 "k8s.io/client-go/kubernetes/typed/storagemigration/v1alpha1"

	storagev1 "k8s.io/client-go/kubernetes/typed/storage/v1"

	storagev1alpha1 "k8s.io/client-go/kubernetes/typed/storage/v1alpha1"

	storagev1beta1 "k8s.io/client-go/kubernetes/typed/storage/v1beta1"

	v1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1"

	v1alpha1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1"

	v1alpha2 "k8s.io/client-go/kubernetes/typed/coordination/v1alpha2"

	v1alpha3 "k8s.io/client-go/kubernetes/typed/resource/v1alpha3"

	v1beta1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1"

	v1beta2 "k8s.io/client-go/kubernetes/typed/apps/v1beta2"

	v1beta3 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta3"

	v2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2"

	v2beta1 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1"

	v2beta2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2"
)

// MockEcosystemClientSet is an autogenerated mock type for the EcosystemClientSet type
type MockEcosystemClientSet struct {
	mock.Mock
}

type MockEcosystemClientSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEcosystemClientSet) EXPECT() *MockEcosystemClientSet_Expecter {
	return &MockEcosystemClientSet_Expecter{mock: &_m.Mock}
}

// AdmissionregistrationV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AdmissionregistrationV1() v1.AdmissionregistrationV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdmissionregistrationV1")
	}

	var r0 v1.AdmissionregistrationV1Interface
	if rf, ok := ret.Get(0).(func() v1.AdmissionregistrationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.AdmissionregistrationV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AdmissionregistrationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1'
type MockEcosystemClientSet_AdmissionregistrationV1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AdmissionregistrationV1() *MockEcosystemClientSet_AdmissionregistrationV1_Call {
	return &MockEcosystemClientSet_AdmissionregistrationV1_Call{Call: _e.mock.On("AdmissionregistrationV1")}
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1_Call) Run(run func()) *MockEcosystemClientSet_AdmissionregistrationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1_Call) Return(_a0 v1.AdmissionregistrationV1Interface) *MockEcosystemClientSet_AdmissionregistrationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1_Call) RunAndReturn(run func() v1.AdmissionregistrationV1Interface) *MockEcosystemClientSet_AdmissionregistrationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AdmissionregistrationV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AdmissionregistrationV1alpha1() v1alpha1.AdmissionregistrationV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdmissionregistrationV1alpha1")
	}

	var r0 v1alpha1.AdmissionregistrationV1alpha1Interface
	if rf, ok := ret.Get(0).(func() v1alpha1.AdmissionregistrationV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.AdmissionregistrationV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1alpha1'
type MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AdmissionregistrationV1alpha1() *MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call {
	return &MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call{Call: _e.mock.On("AdmissionregistrationV1alpha1")}
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call) Return(_a0 v1alpha1.AdmissionregistrationV1alpha1Interface) *MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call) RunAndReturn(run func() v1alpha1.AdmissionregistrationV1alpha1Interface) *MockEcosystemClientSet_AdmissionregistrationV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// AdmissionregistrationV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AdmissionregistrationV1beta1() v1beta1.AdmissionregistrationV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdmissionregistrationV1beta1")
	}

	var r0 v1beta1.AdmissionregistrationV1beta1Interface
	if rf, ok := ret.Get(0).(func() v1beta1.AdmissionregistrationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.AdmissionregistrationV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AdmissionregistrationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1beta1'
type MockEcosystemClientSet_AdmissionregistrationV1beta1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AdmissionregistrationV1beta1() *MockEcosystemClientSet_AdmissionregistrationV1beta1_Call {
	return &MockEcosystemClientSet_AdmissionregistrationV1beta1_Call{Call: _e.mock.On("AdmissionregistrationV1beta1")}
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1beta1_Call) Run(run func()) *MockEcosystemClientSet_AdmissionregistrationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1beta1_Call) Return(_a0 v1beta1.AdmissionregistrationV1beta1Interface) *MockEcosystemClientSet_AdmissionregistrationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AdmissionregistrationV1beta1_Call) RunAndReturn(run func() v1beta1.AdmissionregistrationV1beta1Interface) *MockEcosystemClientSet_AdmissionregistrationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AppsV1() appsv1.AppsV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppsV1")
	}

	var r0 appsv1.AppsV1Interface
	if rf, ok := ret.Get(0).(func() appsv1.AppsV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(appsv1.AppsV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AppsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1'
type MockEcosystemClientSet_AppsV1_Call struct {
	*mock.Call
}

// AppsV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AppsV1() *MockEcosystemClientSet_AppsV1_Call {
	return &MockEcosystemClientSet_AppsV1_Call{Call: _e.mock.On("AppsV1")}
}

func (_c *MockEcosystemClientSet_AppsV1_Call) Run(run func()) *MockEcosystemClientSet_AppsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AppsV1_Call) Return(_a0 appsv1.AppsV1Interface) *MockEcosystemClientSet_AppsV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AppsV1_Call) RunAndReturn(run func() appsv1.AppsV1Interface) *MockEcosystemClientSet_AppsV1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AppsV1beta1() appsv1beta1.AppsV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppsV1beta1")
	}

	var r0 appsv1beta1.AppsV1beta1Interface
	if rf, ok := ret.Get(0).(func() appsv1beta1.AppsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(appsv1beta1.AppsV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AppsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1beta1'
type MockEcosystemClientSet_AppsV1beta1_Call struct {
	*mock.Call
}

// AppsV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AppsV1beta1() *MockEcosystemClientSet_AppsV1beta1_Call {
	return &MockEcosystemClientSet_AppsV1beta1_Call{Call: _e.mock.On("AppsV1beta1")}
}

func (_c *MockEcosystemClientSet_AppsV1beta1_Call) Run(run func()) *MockEcosystemClientSet_AppsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AppsV1beta1_Call) Return(_a0 appsv1beta1.AppsV1beta1Interface) *MockEcosystemClientSet_AppsV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AppsV1beta1_Call) RunAndReturn(run func() appsv1beta1.AppsV1beta1Interface) *MockEcosystemClientSet_AppsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1beta2 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AppsV1beta2() v1beta2.AppsV1beta2Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppsV1beta2")
	}

	var r0 v1beta2.AppsV1beta2Interface
	if rf, ok := ret.Get(0).(func() v1beta2.AppsV1beta2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta2.AppsV1beta2Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AppsV1beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1beta2'
type MockEcosystemClientSet_AppsV1beta2_Call struct {
	*mock.Call
}

// AppsV1beta2 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AppsV1beta2() *MockEcosystemClientSet_AppsV1beta2_Call {
	return &MockEcosystemClientSet_AppsV1beta2_Call{Call: _e.mock.On("AppsV1beta2")}
}

func (_c *MockEcosystemClientSet_AppsV1beta2_Call) Run(run func()) *MockEcosystemClientSet_AppsV1beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AppsV1beta2_Call) Return(_a0 v1beta2.AppsV1beta2Interface) *MockEcosystemClientSet_AppsV1beta2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AppsV1beta2_Call) RunAndReturn(run func() v1beta2.AppsV1beta2Interface) *MockEcosystemClientSet_AppsV1beta2_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AuthenticationV1() authenticationv1.AuthenticationV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticationV1")
	}

	var r0 authenticationv1.AuthenticationV1Interface
	if rf, ok := ret.Get(0).(func() authenticationv1.AuthenticationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authenticationv1.AuthenticationV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AuthenticationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1'
type MockEcosystemClientSet_AuthenticationV1_Call struct {
	*mock.Call
}

// AuthenticationV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AuthenticationV1() *MockEcosystemClientSet_AuthenticationV1_Call {
	return &MockEcosystemClientSet_AuthenticationV1_Call{Call: _e.mock.On("AuthenticationV1")}
}

func (_c *MockEcosystemClientSet_AuthenticationV1_Call) Run(run func()) *MockEcosystemClientSet_AuthenticationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AuthenticationV1_Call) Return(_a0 authenticationv1.AuthenticationV1Interface) *MockEcosystemClientSet_AuthenticationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AuthenticationV1_Call) RunAndReturn(run func() authenticationv1.AuthenticationV1Interface) *MockEcosystemClientSet_AuthenticationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AuthenticationV1alpha1() authenticationv1alpha1.AuthenticationV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticationV1alpha1")
	}

	var r0 authenticationv1alpha1.AuthenticationV1alpha1Interface
	if rf, ok := ret.Get(0).(func() authenticationv1alpha1.AuthenticationV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authenticationv1alpha1.AuthenticationV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AuthenticationV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1alpha1'
type MockEcosystemClientSet_AuthenticationV1alpha1_Call struct {
	*mock.Call
}

// AuthenticationV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AuthenticationV1alpha1() *MockEcosystemClientSet_AuthenticationV1alpha1_Call {
	return &MockEcosystemClientSet_AuthenticationV1alpha1_Call{Call: _e.mock.On("AuthenticationV1alpha1")}
}

func (_c *MockEcosystemClientSet_AuthenticationV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_AuthenticationV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AuthenticationV1alpha1_Call) Return(_a0 authenticationv1alpha1.AuthenticationV1alpha1Interface) *MockEcosystemClientSet_AuthenticationV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AuthenticationV1alpha1_Call) RunAndReturn(run func() authenticationv1alpha1.AuthenticationV1alpha1Interface) *MockEcosystemClientSet_AuthenticationV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AuthenticationV1beta1() authenticationv1beta1.AuthenticationV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticationV1beta1")
	}

	var r0 authenticationv1beta1.AuthenticationV1beta1Interface
	if rf, ok := ret.Get(0).(func() authenticationv1beta1.AuthenticationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authenticationv1beta1.AuthenticationV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AuthenticationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1beta1'
type MockEcosystemClientSet_AuthenticationV1beta1_Call struct {
	*mock.Call
}

// AuthenticationV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AuthenticationV1beta1() *MockEcosystemClientSet_AuthenticationV1beta1_Call {
	return &MockEcosystemClientSet_AuthenticationV1beta1_Call{Call: _e.mock.On("AuthenticationV1beta1")}
}

func (_c *MockEcosystemClientSet_AuthenticationV1beta1_Call) Run(run func()) *MockEcosystemClientSet_AuthenticationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AuthenticationV1beta1_Call) Return(_a0 authenticationv1beta1.AuthenticationV1beta1Interface) *MockEcosystemClientSet_AuthenticationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AuthenticationV1beta1_Call) RunAndReturn(run func() authenticationv1beta1.AuthenticationV1beta1Interface) *MockEcosystemClientSet_AuthenticationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizationV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AuthorizationV1() authorizationv1.AuthorizationV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthorizationV1")
	}

	var r0 authorizationv1.AuthorizationV1Interface
	if rf, ok := ret.Get(0).(func() authorizationv1.AuthorizationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authorizationv1.AuthorizationV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AuthorizationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizationV1'
type MockEcosystemClientSet_AuthorizationV1_Call struct {
	*mock.Call
}

// AuthorizationV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AuthorizationV1() *MockEcosystemClientSet_AuthorizationV1_Call {
	return &MockEcosystemClientSet_AuthorizationV1_Call{Call: _e.mock.On("AuthorizationV1")}
}

func (_c *MockEcosystemClientSet_AuthorizationV1_Call) Run(run func()) *MockEcosystemClientSet_AuthorizationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AuthorizationV1_Call) Return(_a0 authorizationv1.AuthorizationV1Interface) *MockEcosystemClientSet_AuthorizationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AuthorizationV1_Call) RunAndReturn(run func() authorizationv1.AuthorizationV1Interface) *MockEcosystemClientSet_AuthorizationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizationV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AuthorizationV1beta1() authorizationv1beta1.AuthorizationV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthorizationV1beta1")
	}

	var r0 authorizationv1beta1.AuthorizationV1beta1Interface
	if rf, ok := ret.Get(0).(func() authorizationv1beta1.AuthorizationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authorizationv1beta1.AuthorizationV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AuthorizationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizationV1beta1'
type MockEcosystemClientSet_AuthorizationV1beta1_Call struct {
	*mock.Call
}

// AuthorizationV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AuthorizationV1beta1() *MockEcosystemClientSet_AuthorizationV1beta1_Call {
	return &MockEcosystemClientSet_AuthorizationV1beta1_Call{Call: _e.mock.On("AuthorizationV1beta1")}
}

func (_c *MockEcosystemClientSet_AuthorizationV1beta1_Call) Run(run func()) *MockEcosystemClientSet_AuthorizationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AuthorizationV1beta1_Call) Return(_a0 authorizationv1beta1.AuthorizationV1beta1Interface) *MockEcosystemClientSet_AuthorizationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AuthorizationV1beta1_Call) RunAndReturn(run func() authorizationv1beta1.AuthorizationV1beta1Interface) *MockEcosystemClientSet_AuthorizationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AutoscalingV1() autoscalingv1.AutoscalingV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV1")
	}

	var r0 autoscalingv1.AutoscalingV1Interface
	if rf, ok := ret.Get(0).(func() autoscalingv1.AutoscalingV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(autoscalingv1.AutoscalingV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AutoscalingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV1'
type MockEcosystemClientSet_AutoscalingV1_Call struct {
	*mock.Call
}

// AutoscalingV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AutoscalingV1() *MockEcosystemClientSet_AutoscalingV1_Call {
	return &MockEcosystemClientSet_AutoscalingV1_Call{Call: _e.mock.On("AutoscalingV1")}
}

func (_c *MockEcosystemClientSet_AutoscalingV1_Call) Run(run func()) *MockEcosystemClientSet_AutoscalingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV1_Call) Return(_a0 autoscalingv1.AutoscalingV1Interface) *MockEcosystemClientSet_AutoscalingV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV1_Call) RunAndReturn(run func() autoscalingv1.AutoscalingV1Interface) *MockEcosystemClientSet_AutoscalingV1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AutoscalingV2() v2.AutoscalingV2Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV2")
	}

	var r0 v2.AutoscalingV2Interface
	if rf, ok := ret.Get(0).(func() v2.AutoscalingV2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2.AutoscalingV2Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AutoscalingV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2'
type MockEcosystemClientSet_AutoscalingV2_Call struct {
	*mock.Call
}

// AutoscalingV2 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AutoscalingV2() *MockEcosystemClientSet_AutoscalingV2_Call {
	return &MockEcosystemClientSet_AutoscalingV2_Call{Call: _e.mock.On("AutoscalingV2")}
}

func (_c *MockEcosystemClientSet_AutoscalingV2_Call) Run(run func()) *MockEcosystemClientSet_AutoscalingV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV2_Call) Return(_a0 v2.AutoscalingV2Interface) *MockEcosystemClientSet_AutoscalingV2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV2_Call) RunAndReturn(run func() v2.AutoscalingV2Interface) *MockEcosystemClientSet_AutoscalingV2_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AutoscalingV2beta1() v2beta1.AutoscalingV2beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV2beta1")
	}

	var r0 v2beta1.AutoscalingV2beta1Interface
	if rf, ok := ret.Get(0).(func() v2beta1.AutoscalingV2beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2beta1.AutoscalingV2beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AutoscalingV2beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2beta1'
type MockEcosystemClientSet_AutoscalingV2beta1_Call struct {
	*mock.Call
}

// AutoscalingV2beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AutoscalingV2beta1() *MockEcosystemClientSet_AutoscalingV2beta1_Call {
	return &MockEcosystemClientSet_AutoscalingV2beta1_Call{Call: _e.mock.On("AutoscalingV2beta1")}
}

func (_c *MockEcosystemClientSet_AutoscalingV2beta1_Call) Run(run func()) *MockEcosystemClientSet_AutoscalingV2beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV2beta1_Call) Return(_a0 v2beta1.AutoscalingV2beta1Interface) *MockEcosystemClientSet_AutoscalingV2beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV2beta1_Call) RunAndReturn(run func() v2beta1.AutoscalingV2beta1Interface) *MockEcosystemClientSet_AutoscalingV2beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2beta2 provides a mock function with no fields
func (_m *MockEcosystemClientSet) AutoscalingV2beta2() v2beta2.AutoscalingV2beta2Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV2beta2")
	}

	var r0 v2beta2.AutoscalingV2beta2Interface
	if rf, ok := ret.Get(0).(func() v2beta2.AutoscalingV2beta2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2beta2.AutoscalingV2beta2Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_AutoscalingV2beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2beta2'
type MockEcosystemClientSet_AutoscalingV2beta2_Call struct {
	*mock.Call
}

// AutoscalingV2beta2 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) AutoscalingV2beta2() *MockEcosystemClientSet_AutoscalingV2beta2_Call {
	return &MockEcosystemClientSet_AutoscalingV2beta2_Call{Call: _e.mock.On("AutoscalingV2beta2")}
}

func (_c *MockEcosystemClientSet_AutoscalingV2beta2_Call) Run(run func()) *MockEcosystemClientSet_AutoscalingV2beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV2beta2_Call) Return(_a0 v2beta2.AutoscalingV2beta2Interface) *MockEcosystemClientSet_AutoscalingV2beta2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_AutoscalingV2beta2_Call) RunAndReturn(run func() v2beta2.AutoscalingV2beta2Interface) *MockEcosystemClientSet_AutoscalingV2beta2_Call {
	_c.Call.Return(run)
	return _c
}

// BatchV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) BatchV1() batchv1.BatchV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatchV1")
	}

	var r0 batchv1.BatchV1Interface
	if rf, ok := ret.Get(0).(func() batchv1.BatchV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(batchv1.BatchV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_BatchV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchV1'
type MockEcosystemClientSet_BatchV1_Call struct {
	*mock.Call
}

// BatchV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) BatchV1() *MockEcosystemClientSet_BatchV1_Call {
	return &MockEcosystemClientSet_BatchV1_Call{Call: _e.mock.On("BatchV1")}
}

func (_c *MockEcosystemClientSet_BatchV1_Call) Run(run func()) *MockEcosystemClientSet_BatchV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_BatchV1_Call) Return(_a0 batchv1.BatchV1Interface) *MockEcosystemClientSet_BatchV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_BatchV1_Call) RunAndReturn(run func() batchv1.BatchV1Interface) *MockEcosystemClientSet_BatchV1_Call {
	_c.Call.Return(run)
	return _c
}

// BatchV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) BatchV1beta1() batchv1beta1.BatchV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatchV1beta1")
	}

	var r0 batchv1beta1.BatchV1beta1Interface
	if rf, ok := ret.Get(0).(func() batchv1beta1.BatchV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(batchv1beta1.BatchV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_BatchV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchV1beta1'
type MockEcosystemClientSet_BatchV1beta1_Call struct {
	*mock.Call
}

// BatchV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) BatchV1beta1() *MockEcosystemClientSet_BatchV1beta1_Call {
	return &MockEcosystemClientSet_BatchV1beta1_Call{Call: _e.mock.On("BatchV1beta1")}
}

func (_c *MockEcosystemClientSet_BatchV1beta1_Call) Run(run func()) *MockEcosystemClientSet_BatchV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_BatchV1beta1_Call) Return(_a0 batchv1beta1.BatchV1beta1Interface) *MockEcosystemClientSet_BatchV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_BatchV1beta1_Call) RunAndReturn(run func() batchv1beta1.BatchV1beta1Interface) *MockEcosystemClientSet_BatchV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) CertificatesV1() certificatesv1.CertificatesV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificatesV1")
	}

	var r0 certificatesv1.CertificatesV1Interface
	if rf, ok := ret.Get(0).(func() certificatesv1.CertificatesV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificatesv1.CertificatesV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_CertificatesV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1'
type MockEcosystemClientSet_CertificatesV1_Call struct {
	*mock.Call
}

// CertificatesV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) CertificatesV1() *MockEcosystemClientSet_CertificatesV1_Call {
	return &MockEcosystemClientSet_CertificatesV1_Call{Call: _e.mock.On("CertificatesV1")}
}

func (_c *MockEcosystemClientSet_CertificatesV1_Call) Run(run func()) *MockEcosystemClientSet_CertificatesV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_CertificatesV1_Call) Return(_a0 certificatesv1.CertificatesV1Interface) *MockEcosystemClientSet_CertificatesV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_CertificatesV1_Call) RunAndReturn(run func() certificatesv1.CertificatesV1Interface) *MockEcosystemClientSet_CertificatesV1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) CertificatesV1alpha1() certificatesv1alpha1.CertificatesV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificatesV1alpha1")
	}

	var r0 certificatesv1alpha1.CertificatesV1alpha1Interface
	if rf, ok := ret.Get(0).(func() certificatesv1alpha1.CertificatesV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificatesv1alpha1.CertificatesV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_CertificatesV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1alpha1'
type MockEcosystemClientSet_CertificatesV1alpha1_Call struct {
	*mock.Call
}

// CertificatesV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) CertificatesV1alpha1() *MockEcosystemClientSet_CertificatesV1alpha1_Call {
	return &MockEcosystemClientSet_CertificatesV1alpha1_Call{Call: _e.mock.On("CertificatesV1alpha1")}
}

func (_c *MockEcosystemClientSet_CertificatesV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_CertificatesV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_CertificatesV1alpha1_Call) Return(_a0 certificatesv1alpha1.CertificatesV1alpha1Interface) *MockEcosystemClientSet_CertificatesV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_CertificatesV1alpha1_Call) RunAndReturn(run func() certificatesv1alpha1.CertificatesV1alpha1Interface) *MockEcosystemClientSet_CertificatesV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) CertificatesV1beta1() certificatesv1beta1.CertificatesV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificatesV1beta1")
	}

	var r0 certificatesv1beta1.CertificatesV1beta1Interface
	if rf, ok := ret.Get(0).(func() certificatesv1beta1.CertificatesV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificatesv1beta1.CertificatesV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_CertificatesV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1beta1'
type MockEcosystemClientSet_CertificatesV1beta1_Call struct {
	*mock.Call
}

// CertificatesV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) CertificatesV1beta1() *MockEcosystemClientSet_CertificatesV1beta1_Call {
	return &MockEcosystemClientSet_CertificatesV1beta1_Call{Call: _e.mock.On("CertificatesV1beta1")}
}

func (_c *MockEcosystemClientSet_CertificatesV1beta1_Call) Run(run func()) *MockEcosystemClientSet_CertificatesV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_CertificatesV1beta1_Call) Return(_a0 certificatesv1beta1.CertificatesV1beta1Interface) *MockEcosystemClientSet_CertificatesV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_CertificatesV1beta1_Call) RunAndReturn(run func() certificatesv1beta1.CertificatesV1beta1Interface) *MockEcosystemClientSet_CertificatesV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) CoordinationV1() coordinationv1.CoordinationV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoordinationV1")
	}

	var r0 coordinationv1.CoordinationV1Interface
	if rf, ok := ret.Get(0).(func() coordinationv1.CoordinationV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(coordinationv1.CoordinationV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_CoordinationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1'
type MockEcosystemClientSet_CoordinationV1_Call struct {
	*mock.Call
}

// CoordinationV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) CoordinationV1() *MockEcosystemClientSet_CoordinationV1_Call {
	return &MockEcosystemClientSet_CoordinationV1_Call{Call: _e.mock.On("CoordinationV1")}
}

func (_c *MockEcosystemClientSet_CoordinationV1_Call) Run(run func()) *MockEcosystemClientSet_CoordinationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_CoordinationV1_Call) Return(_a0 coordinationv1.CoordinationV1Interface) *MockEcosystemClientSet_CoordinationV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_CoordinationV1_Call) RunAndReturn(run func() coordinationv1.CoordinationV1Interface) *MockEcosystemClientSet_CoordinationV1_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1alpha2 provides a mock function with no fields
func (_m *MockEcosystemClientSet) CoordinationV1alpha2() v1alpha2.CoordinationV1alpha2Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoordinationV1alpha2")
	}

	var r0 v1alpha2.CoordinationV1alpha2Interface
	if rf, ok := ret.Get(0).(func() v1alpha2.CoordinationV1alpha2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha2.CoordinationV1alpha2Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_CoordinationV1alpha2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1alpha2'
type MockEcosystemClientSet_CoordinationV1alpha2_Call struct {
	*mock.Call
}

// CoordinationV1alpha2 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) CoordinationV1alpha2() *MockEcosystemClientSet_CoordinationV1alpha2_Call {
	return &MockEcosystemClientSet_CoordinationV1alpha2_Call{Call: _e.mock.On("CoordinationV1alpha2")}
}

func (_c *MockEcosystemClientSet_CoordinationV1alpha2_Call) Run(run func()) *MockEcosystemClientSet_CoordinationV1alpha2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_CoordinationV1alpha2_Call) Return(_a0 v1alpha2.CoordinationV1alpha2Interface) *MockEcosystemClientSet_CoordinationV1alpha2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_CoordinationV1alpha2_Call) RunAndReturn(run func() v1alpha2.CoordinationV1alpha2Interface) *MockEcosystemClientSet_CoordinationV1alpha2_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) CoordinationV1beta1() coordinationv1beta1.CoordinationV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoordinationV1beta1")
	}

	var r0 coordinationv1beta1.CoordinationV1beta1Interface
	if rf, ok := ret.Get(0).(func() coordinationv1beta1.CoordinationV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(coordinationv1beta1.CoordinationV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_CoordinationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1beta1'
type MockEcosystemClientSet_CoordinationV1beta1_Call struct {
	*mock.Call
}

// CoordinationV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) CoordinationV1beta1() *MockEcosystemClientSet_CoordinationV1beta1_Call {
	return &MockEcosystemClientSet_CoordinationV1beta1_Call{Call: _e.mock.On("CoordinationV1beta1")}
}

func (_c *MockEcosystemClientSet_CoordinationV1beta1_Call) Run(run func()) *MockEcosystemClientSet_CoordinationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_CoordinationV1beta1_Call) Return(_a0 coordinationv1beta1.CoordinationV1beta1Interface) *MockEcosystemClientSet_CoordinationV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_CoordinationV1beta1_Call) RunAndReturn(run func() coordinationv1beta1.CoordinationV1beta1Interface) *MockEcosystemClientSet_CoordinationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CoreV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) CoreV1() corev1.CoreV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoreV1")
	}

	var r0 corev1.CoreV1Interface
	if rf, ok := ret.Get(0).(func() corev1.CoreV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(corev1.CoreV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_CoreV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoreV1'
type MockEcosystemClientSet_CoreV1_Call struct {
	*mock.Call
}

// CoreV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) CoreV1() *MockEcosystemClientSet_CoreV1_Call {
	return &MockEcosystemClientSet_CoreV1_Call{Call: _e.mock.On("CoreV1")}
}

func (_c *MockEcosystemClientSet_CoreV1_Call) Run(run func()) *MockEcosystemClientSet_CoreV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_CoreV1_Call) Return(_a0 corev1.CoreV1Interface) *MockEcosystemClientSet_CoreV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_CoreV1_Call) RunAndReturn(run func() corev1.CoreV1Interface) *MockEcosystemClientSet_CoreV1_Call {
	_c.Call.Return(run)
	return _c
}

// Discovery provides a mock function with no fields
func (_m *MockEcosystemClientSet) Discovery() discovery.DiscoveryInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Discovery")
	}

	var r0 discovery.DiscoveryInterface
	if rf, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}

	return r0
}

// MockEcosystemClientSet_Discovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discovery'
type MockEcosystemClientSet_Discovery_Call struct {
	*mock.Call
}

// Discovery is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) Discovery() *MockEcosystemClientSet_Discovery_Call {
	return &MockEcosystemClientSet_Discovery_Call{Call: _e.mock.On("Discovery")}
}

func (_c *MockEcosystemClientSet_Discovery_Call) Run(run func()) *MockEcosystemClientSet_Discovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_Discovery_Call) Return(_a0 discovery.DiscoveryInterface) *MockEcosystemClientSet_Discovery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_Discovery_Call) RunAndReturn(run func() discovery.DiscoveryInterface) *MockEcosystemClientSet_Discovery_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoveryV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) DiscoveryV1() discoveryv1.DiscoveryV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoveryV1")
	}

	var r0 discoveryv1.DiscoveryV1Interface
	if rf, ok := ret.Get(0).(func() discoveryv1.DiscoveryV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discoveryv1.DiscoveryV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_DiscoveryV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveryV1'
type MockEcosystemClientSet_DiscoveryV1_Call struct {
	*mock.Call
}

// DiscoveryV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) DiscoveryV1() *MockEcosystemClientSet_DiscoveryV1_Call {
	return &MockEcosystemClientSet_DiscoveryV1_Call{Call: _e.mock.On("DiscoveryV1")}
}

func (_c *MockEcosystemClientSet_DiscoveryV1_Call) Run(run func()) *MockEcosystemClientSet_DiscoveryV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_DiscoveryV1_Call) Return(_a0 discoveryv1.DiscoveryV1Interface) *MockEcosystemClientSet_DiscoveryV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_DiscoveryV1_Call) RunAndReturn(run func() discoveryv1.DiscoveryV1Interface) *MockEcosystemClientSet_DiscoveryV1_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoveryV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) DiscoveryV1beta1() discoveryv1beta1.DiscoveryV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoveryV1beta1")
	}

	var r0 discoveryv1beta1.DiscoveryV1beta1Interface
	if rf, ok := ret.Get(0).(func() discoveryv1beta1.DiscoveryV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discoveryv1beta1.DiscoveryV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_DiscoveryV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveryV1beta1'
type MockEcosystemClientSet_DiscoveryV1beta1_Call struct {
	*mock.Call
}

// DiscoveryV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) DiscoveryV1beta1() *MockEcosystemClientSet_DiscoveryV1beta1_Call {
	return &MockEcosystemClientSet_DiscoveryV1beta1_Call{Call: _e.mock.On("DiscoveryV1beta1")}
}

func (_c *MockEcosystemClientSet_DiscoveryV1beta1_Call) Run(run func()) *MockEcosystemClientSet_DiscoveryV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_DiscoveryV1beta1_Call) Return(_a0 discoveryv1beta1.DiscoveryV1beta1Interface) *MockEcosystemClientSet_DiscoveryV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_DiscoveryV1beta1_Call) RunAndReturn(run func() discoveryv1beta1.DiscoveryV1beta1Interface) *MockEcosystemClientSet_DiscoveryV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// EventsV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) EventsV1() eventsv1.EventsV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventsV1")
	}

	var r0 eventsv1.EventsV1Interface
	if rf, ok := ret.Get(0).(func() eventsv1.EventsV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eventsv1.EventsV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_EventsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsV1'
type MockEcosystemClientSet_EventsV1_Call struct {
	*mock.Call
}

// EventsV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) EventsV1() *MockEcosystemClientSet_EventsV1_Call {
	return &MockEcosystemClientSet_EventsV1_Call{Call: _e.mock.On("EventsV1")}
}

func (_c *MockEcosystemClientSet_EventsV1_Call) Run(run func()) *MockEcosystemClientSet_EventsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_EventsV1_Call) Return(_a0 eventsv1.EventsV1Interface) *MockEcosystemClientSet_EventsV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_EventsV1_Call) RunAndReturn(run func() eventsv1.EventsV1Interface) *MockEcosystemClientSet_EventsV1_Call {
	_c.Call.Return(run)
	return _c
}

// EventsV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) EventsV1beta1() eventsv1beta1.EventsV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventsV1beta1")
	}

	var r0 eventsv1beta1.EventsV1beta1Interface
	if rf, ok := ret.Get(0).(func() eventsv1beta1.EventsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eventsv1beta1.EventsV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_EventsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsV1beta1'
type MockEcosystemClientSet_EventsV1beta1_Call struct {
	*mock.Call
}

// EventsV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) EventsV1beta1() *MockEcosystemClientSet_EventsV1beta1_Call {
	return &MockEcosystemClientSet_EventsV1beta1_Call{Call: _e.mock.On("EventsV1beta1")}
}

func (_c *MockEcosystemClientSet_EventsV1beta1_Call) Run(run func()) *MockEcosystemClientSet_EventsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_EventsV1beta1_Call) Return(_a0 eventsv1beta1.EventsV1beta1Interface) *MockEcosystemClientSet_EventsV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_EventsV1beta1_Call) RunAndReturn(run func() eventsv1beta1.EventsV1beta1Interface) *MockEcosystemClientSet_EventsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ExtensionsV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) ExtensionsV1beta1() extensionsv1beta1.ExtensionsV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExtensionsV1beta1")
	}

	var r0 extensionsv1beta1.ExtensionsV1beta1Interface
	if rf, ok := ret.Get(0).(func() extensionsv1beta1.ExtensionsV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(extensionsv1beta1.ExtensionsV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_ExtensionsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtensionsV1beta1'
type MockEcosystemClientSet_ExtensionsV1beta1_Call struct {
	*mock.Call
}

// ExtensionsV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) ExtensionsV1beta1() *MockEcosystemClientSet_ExtensionsV1beta1_Call {
	return &MockEcosystemClientSet_ExtensionsV1beta1_Call{Call: _e.mock.On("ExtensionsV1beta1")}
}

func (_c *MockEcosystemClientSet_ExtensionsV1beta1_Call) Run(run func()) *MockEcosystemClientSet_ExtensionsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_ExtensionsV1beta1_Call) Return(_a0 extensionsv1beta1.ExtensionsV1beta1Interface) *MockEcosystemClientSet_ExtensionsV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_ExtensionsV1beta1_Call) RunAndReturn(run func() extensionsv1beta1.ExtensionsV1beta1Interface) *MockEcosystemClientSet_ExtensionsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) FlowcontrolV1() flowcontrolv1.FlowcontrolV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1")
	}

	var r0 flowcontrolv1.FlowcontrolV1Interface
	if rf, ok := ret.Get(0).(func() flowcontrolv1.FlowcontrolV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flowcontrolv1.FlowcontrolV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_FlowcontrolV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1'
type MockEcosystemClientSet_FlowcontrolV1_Call struct {
	*mock.Call
}

// FlowcontrolV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) FlowcontrolV1() *MockEcosystemClientSet_FlowcontrolV1_Call {
	return &MockEcosystemClientSet_FlowcontrolV1_Call{Call: _e.mock.On("FlowcontrolV1")}
}

func (_c *MockEcosystemClientSet_FlowcontrolV1_Call) Run(run func()) *MockEcosystemClientSet_FlowcontrolV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1_Call) Return(_a0 flowcontrolv1.FlowcontrolV1Interface) *MockEcosystemClientSet_FlowcontrolV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1_Call) RunAndReturn(run func() flowcontrolv1.FlowcontrolV1Interface) *MockEcosystemClientSet_FlowcontrolV1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) FlowcontrolV1beta1() flowcontrolv1beta1.FlowcontrolV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1beta1")
	}

	var r0 flowcontrolv1beta1.FlowcontrolV1beta1Interface
	if rf, ok := ret.Get(0).(func() flowcontrolv1beta1.FlowcontrolV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flowcontrolv1beta1.FlowcontrolV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_FlowcontrolV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta1'
type MockEcosystemClientSet_FlowcontrolV1beta1_Call struct {
	*mock.Call
}

// FlowcontrolV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) FlowcontrolV1beta1() *MockEcosystemClientSet_FlowcontrolV1beta1_Call {
	return &MockEcosystemClientSet_FlowcontrolV1beta1_Call{Call: _e.mock.On("FlowcontrolV1beta1")}
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta1_Call) Run(run func()) *MockEcosystemClientSet_FlowcontrolV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta1_Call) Return(_a0 flowcontrolv1beta1.FlowcontrolV1beta1Interface) *MockEcosystemClientSet_FlowcontrolV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta1_Call) RunAndReturn(run func() flowcontrolv1beta1.FlowcontrolV1beta1Interface) *MockEcosystemClientSet_FlowcontrolV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta2 provides a mock function with no fields
func (_m *MockEcosystemClientSet) FlowcontrolV1beta2() flowcontrolv1beta2.FlowcontrolV1beta2Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1beta2")
	}

	var r0 flowcontrolv1beta2.FlowcontrolV1beta2Interface
	if rf, ok := ret.Get(0).(func() flowcontrolv1beta2.FlowcontrolV1beta2Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flowcontrolv1beta2.FlowcontrolV1beta2Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_FlowcontrolV1beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta2'
type MockEcosystemClientSet_FlowcontrolV1beta2_Call struct {
	*mock.Call
}

// FlowcontrolV1beta2 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) FlowcontrolV1beta2() *MockEcosystemClientSet_FlowcontrolV1beta2_Call {
	return &MockEcosystemClientSet_FlowcontrolV1beta2_Call{Call: _e.mock.On("FlowcontrolV1beta2")}
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta2_Call) Run(run func()) *MockEcosystemClientSet_FlowcontrolV1beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta2_Call) Return(_a0 flowcontrolv1beta2.FlowcontrolV1beta2Interface) *MockEcosystemClientSet_FlowcontrolV1beta2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta2_Call) RunAndReturn(run func() flowcontrolv1beta2.FlowcontrolV1beta2Interface) *MockEcosystemClientSet_FlowcontrolV1beta2_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta3 provides a mock function with no fields
func (_m *MockEcosystemClientSet) FlowcontrolV1beta3() v1beta3.FlowcontrolV1beta3Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1beta3")
	}

	var r0 v1beta3.FlowcontrolV1beta3Interface
	if rf, ok := ret.Get(0).(func() v1beta3.FlowcontrolV1beta3Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta3.FlowcontrolV1beta3Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_FlowcontrolV1beta3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta3'
type MockEcosystemClientSet_FlowcontrolV1beta3_Call struct {
	*mock.Call
}

// FlowcontrolV1beta3 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) FlowcontrolV1beta3() *MockEcosystemClientSet_FlowcontrolV1beta3_Call {
	return &MockEcosystemClientSet_FlowcontrolV1beta3_Call{Call: _e.mock.On("FlowcontrolV1beta3")}
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta3_Call) Run(run func()) *MockEcosystemClientSet_FlowcontrolV1beta3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta3_Call) Return(_a0 v1beta3.FlowcontrolV1beta3Interface) *MockEcosystemClientSet_FlowcontrolV1beta3_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_FlowcontrolV1beta3_Call) RunAndReturn(run func() v1beta3.FlowcontrolV1beta3Interface) *MockEcosystemClientSet_FlowcontrolV1beta3_Call {
	_c.Call.Return(run)
	return _c
}

// InternalV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) InternalV1alpha1() apiserverinternalv1alpha1.InternalV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InternalV1alpha1")
	}

	var r0 apiserverinternalv1alpha1.InternalV1alpha1Interface
	if rf, ok := ret.Get(0).(func() apiserverinternalv1alpha1.InternalV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiserverinternalv1alpha1.InternalV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_InternalV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InternalV1alpha1'
type MockEcosystemClientSet_InternalV1alpha1_Call struct {
	*mock.Call
}

// InternalV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) InternalV1alpha1() *MockEcosystemClientSet_InternalV1alpha1_Call {
	return &MockEcosystemClientSet_InternalV1alpha1_Call{Call: _e.mock.On("InternalV1alpha1")}
}

func (_c *MockEcosystemClientSet_InternalV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_InternalV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_InternalV1alpha1_Call) Return(_a0 apiserverinternalv1alpha1.InternalV1alpha1Interface) *MockEcosystemClientSet_InternalV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_InternalV1alpha1_Call) RunAndReturn(run func() apiserverinternalv1alpha1.InternalV1alpha1Interface) *MockEcosystemClientSet_InternalV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) NetworkingV1() networkingv1.NetworkingV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NetworkingV1")
	}

	var r0 networkingv1.NetworkingV1Interface
	if rf, ok := ret.Get(0).(func() networkingv1.NetworkingV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkingv1.NetworkingV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_NetworkingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1'
type MockEcosystemClientSet_NetworkingV1_Call struct {
	*mock.Call
}

// NetworkingV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) NetworkingV1() *MockEcosystemClientSet_NetworkingV1_Call {
	return &MockEcosystemClientSet_NetworkingV1_Call{Call: _e.mock.On("NetworkingV1")}
}

func (_c *MockEcosystemClientSet_NetworkingV1_Call) Run(run func()) *MockEcosystemClientSet_NetworkingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_NetworkingV1_Call) Return(_a0 networkingv1.NetworkingV1Interface) *MockEcosystemClientSet_NetworkingV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_NetworkingV1_Call) RunAndReturn(run func() networkingv1.NetworkingV1Interface) *MockEcosystemClientSet_NetworkingV1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) NetworkingV1alpha1() networkingv1alpha1.NetworkingV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NetworkingV1alpha1")
	}

	var r0 networkingv1alpha1.NetworkingV1alpha1Interface
	if rf, ok := ret.Get(0).(func() networkingv1alpha1.NetworkingV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkingv1alpha1.NetworkingV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_NetworkingV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1alpha1'
type MockEcosystemClientSet_NetworkingV1alpha1_Call struct {
	*mock.Call
}

// NetworkingV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) NetworkingV1alpha1() *MockEcosystemClientSet_NetworkingV1alpha1_Call {
	return &MockEcosystemClientSet_NetworkingV1alpha1_Call{Call: _e.mock.On("NetworkingV1alpha1")}
}

func (_c *MockEcosystemClientSet_NetworkingV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_NetworkingV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_NetworkingV1alpha1_Call) Return(_a0 networkingv1alpha1.NetworkingV1alpha1Interface) *MockEcosystemClientSet_NetworkingV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_NetworkingV1alpha1_Call) RunAndReturn(run func() networkingv1alpha1.NetworkingV1alpha1Interface) *MockEcosystemClientSet_NetworkingV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) NetworkingV1beta1() networkingv1beta1.NetworkingV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NetworkingV1beta1")
	}

	var r0 networkingv1beta1.NetworkingV1beta1Interface
	if rf, ok := ret.Get(0).(func() networkingv1beta1.NetworkingV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkingv1beta1.NetworkingV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_NetworkingV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1beta1'
type MockEcosystemClientSet_NetworkingV1beta1_Call struct {
	*mock.Call
}

// NetworkingV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) NetworkingV1beta1() *MockEcosystemClientSet_NetworkingV1beta1_Call {
	return &MockEcosystemClientSet_NetworkingV1beta1_Call{Call: _e.mock.On("NetworkingV1beta1")}
}

func (_c *MockEcosystemClientSet_NetworkingV1beta1_Call) Run(run func()) *MockEcosystemClientSet_NetworkingV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_NetworkingV1beta1_Call) Return(_a0 networkingv1beta1.NetworkingV1beta1Interface) *MockEcosystemClientSet_NetworkingV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_NetworkingV1beta1_Call) RunAndReturn(run func() networkingv1beta1.NetworkingV1beta1Interface) *MockEcosystemClientSet_NetworkingV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) NodeV1() nodev1.NodeV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeV1")
	}

	var r0 nodev1.NodeV1Interface
	if rf, ok := ret.Get(0).(func() nodev1.NodeV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nodev1.NodeV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_NodeV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1'
type MockEcosystemClientSet_NodeV1_Call struct {
	*mock.Call
}

// NodeV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) NodeV1() *MockEcosystemClientSet_NodeV1_Call {
	return &MockEcosystemClientSet_NodeV1_Call{Call: _e.mock.On("NodeV1")}
}

func (_c *MockEcosystemClientSet_NodeV1_Call) Run(run func()) *MockEcosystemClientSet_NodeV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_NodeV1_Call) Return(_a0 nodev1.NodeV1Interface) *MockEcosystemClientSet_NodeV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_NodeV1_Call) RunAndReturn(run func() nodev1.NodeV1Interface) *MockEcosystemClientSet_NodeV1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) NodeV1alpha1() nodev1alpha1.NodeV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeV1alpha1")
	}

	var r0 nodev1alpha1.NodeV1alpha1Interface
	if rf, ok := ret.Get(0).(func() nodev1alpha1.NodeV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nodev1alpha1.NodeV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_NodeV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1alpha1'
type MockEcosystemClientSet_NodeV1alpha1_Call struct {
	*mock.Call
}

// NodeV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) NodeV1alpha1() *MockEcosystemClientSet_NodeV1alpha1_Call {
	return &MockEcosystemClientSet_NodeV1alpha1_Call{Call: _e.mock.On("NodeV1alpha1")}
}

func (_c *MockEcosystemClientSet_NodeV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_NodeV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_NodeV1alpha1_Call) Return(_a0 nodev1alpha1.NodeV1alpha1Interface) *MockEcosystemClientSet_NodeV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_NodeV1alpha1_Call) RunAndReturn(run func() nodev1alpha1.NodeV1alpha1Interface) *MockEcosystemClientSet_NodeV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) NodeV1beta1() nodev1beta1.NodeV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeV1beta1")
	}

	var r0 nodev1beta1.NodeV1beta1Interface
	if rf, ok := ret.Get(0).(func() nodev1beta1.NodeV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nodev1beta1.NodeV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_NodeV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1beta1'
type MockEcosystemClientSet_NodeV1beta1_Call struct {
	*mock.Call
}

// NodeV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) NodeV1beta1() *MockEcosystemClientSet_NodeV1beta1_Call {
	return &MockEcosystemClientSet_NodeV1beta1_Call{Call: _e.mock.On("NodeV1beta1")}
}

func (_c *MockEcosystemClientSet_NodeV1beta1_Call) Run(run func()) *MockEcosystemClientSet_NodeV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_NodeV1beta1_Call) Return(_a0 nodev1beta1.NodeV1beta1Interface) *MockEcosystemClientSet_NodeV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_NodeV1beta1_Call) RunAndReturn(run func() nodev1beta1.NodeV1beta1Interface) *MockEcosystemClientSet_NodeV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) PolicyV1() policyv1.PolicyV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PolicyV1")
	}

	var r0 policyv1.PolicyV1Interface
	if rf, ok := ret.Get(0).(func() policyv1.PolicyV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policyv1.PolicyV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_PolicyV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyV1'
type MockEcosystemClientSet_PolicyV1_Call struct {
	*mock.Call
}

// PolicyV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) PolicyV1() *MockEcosystemClientSet_PolicyV1_Call {
	return &MockEcosystemClientSet_PolicyV1_Call{Call: _e.mock.On("PolicyV1")}
}

func (_c *MockEcosystemClientSet_PolicyV1_Call) Run(run func()) *MockEcosystemClientSet_PolicyV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_PolicyV1_Call) Return(_a0 policyv1.PolicyV1Interface) *MockEcosystemClientSet_PolicyV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_PolicyV1_Call) RunAndReturn(run func() policyv1.PolicyV1Interface) *MockEcosystemClientSet_PolicyV1_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) PolicyV1beta1() policyv1beta1.PolicyV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PolicyV1beta1")
	}

	var r0 policyv1beta1.PolicyV1beta1Interface
	if rf, ok := ret.Get(0).(func() policyv1beta1.PolicyV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(policyv1beta1.PolicyV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_PolicyV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyV1beta1'
type MockEcosystemClientSet_PolicyV1beta1_Call struct {
	*mock.Call
}

// PolicyV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) PolicyV1beta1() *MockEcosystemClientSet_PolicyV1beta1_Call {
	return &MockEcosystemClientSet_PolicyV1beta1_Call{Call: _e.mock.On("PolicyV1beta1")}
}

func (_c *MockEcosystemClientSet_PolicyV1beta1_Call) Run(run func()) *MockEcosystemClientSet_PolicyV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_PolicyV1beta1_Call) Return(_a0 policyv1beta1.PolicyV1beta1Interface) *MockEcosystemClientSet_PolicyV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_PolicyV1beta1_Call) RunAndReturn(run func() policyv1beta1.PolicyV1beta1Interface) *MockEcosystemClientSet_PolicyV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) RbacV1() rbacv1.RbacV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RbacV1")
	}

	var r0 rbacv1.RbacV1Interface
	if rf, ok := ret.Get(0).(func() rbacv1.RbacV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rbacv1.RbacV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_RbacV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1'
type MockEcosystemClientSet_RbacV1_Call struct {
	*mock.Call
}

// RbacV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) RbacV1() *MockEcosystemClientSet_RbacV1_Call {
	return &MockEcosystemClientSet_RbacV1_Call{Call: _e.mock.On("RbacV1")}
}

func (_c *MockEcosystemClientSet_RbacV1_Call) Run(run func()) *MockEcosystemClientSet_RbacV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_RbacV1_Call) Return(_a0 rbacv1.RbacV1Interface) *MockEcosystemClientSet_RbacV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_RbacV1_Call) RunAndReturn(run func() rbacv1.RbacV1Interface) *MockEcosystemClientSet_RbacV1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) RbacV1alpha1() rbacv1alpha1.RbacV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RbacV1alpha1")
	}

	var r0 rbacv1alpha1.RbacV1alpha1Interface
	if rf, ok := ret.Get(0).(func() rbacv1alpha1.RbacV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rbacv1alpha1.RbacV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_RbacV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1alpha1'
type MockEcosystemClientSet_RbacV1alpha1_Call struct {
	*mock.Call
}

// RbacV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) RbacV1alpha1() *MockEcosystemClientSet_RbacV1alpha1_Call {
	return &MockEcosystemClientSet_RbacV1alpha1_Call{Call: _e.mock.On("RbacV1alpha1")}
}

func (_c *MockEcosystemClientSet_RbacV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_RbacV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_RbacV1alpha1_Call) Return(_a0 rbacv1alpha1.RbacV1alpha1Interface) *MockEcosystemClientSet_RbacV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_RbacV1alpha1_Call) RunAndReturn(run func() rbacv1alpha1.RbacV1alpha1Interface) *MockEcosystemClientSet_RbacV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) RbacV1beta1() rbacv1beta1.RbacV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RbacV1beta1")
	}

	var r0 rbacv1beta1.RbacV1beta1Interface
	if rf, ok := ret.Get(0).(func() rbacv1beta1.RbacV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rbacv1beta1.RbacV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_RbacV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1beta1'
type MockEcosystemClientSet_RbacV1beta1_Call struct {
	*mock.Call
}

// RbacV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) RbacV1beta1() *MockEcosystemClientSet_RbacV1beta1_Call {
	return &MockEcosystemClientSet_RbacV1beta1_Call{Call: _e.mock.On("RbacV1beta1")}
}

func (_c *MockEcosystemClientSet_RbacV1beta1_Call) Run(run func()) *MockEcosystemClientSet_RbacV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_RbacV1beta1_Call) Return(_a0 rbacv1beta1.RbacV1beta1Interface) *MockEcosystemClientSet_RbacV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_RbacV1beta1_Call) RunAndReturn(run func() rbacv1beta1.RbacV1beta1Interface) *MockEcosystemClientSet_RbacV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceV1alpha3 provides a mock function with no fields
func (_m *MockEcosystemClientSet) ResourceV1alpha3() v1alpha3.ResourceV1alpha3Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResourceV1alpha3")
	}

	var r0 v1alpha3.ResourceV1alpha3Interface
	if rf, ok := ret.Get(0).(func() v1alpha3.ResourceV1alpha3Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha3.ResourceV1alpha3Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_ResourceV1alpha3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceV1alpha3'
type MockEcosystemClientSet_ResourceV1alpha3_Call struct {
	*mock.Call
}

// ResourceV1alpha3 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) ResourceV1alpha3() *MockEcosystemClientSet_ResourceV1alpha3_Call {
	return &MockEcosystemClientSet_ResourceV1alpha3_Call{Call: _e.mock.On("ResourceV1alpha3")}
}

func (_c *MockEcosystemClientSet_ResourceV1alpha3_Call) Run(run func()) *MockEcosystemClientSet_ResourceV1alpha3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_ResourceV1alpha3_Call) Return(_a0 v1alpha3.ResourceV1alpha3Interface) *MockEcosystemClientSet_ResourceV1alpha3_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_ResourceV1alpha3_Call) RunAndReturn(run func() v1alpha3.ResourceV1alpha3Interface) *MockEcosystemClientSet_ResourceV1alpha3_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) ResourceV1beta1() resourcev1beta1.ResourceV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResourceV1beta1")
	}

	var r0 resourcev1beta1.ResourceV1beta1Interface
	if rf, ok := ret.Get(0).(func() resourcev1beta1.ResourceV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resourcev1beta1.ResourceV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_ResourceV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceV1beta1'
type MockEcosystemClientSet_ResourceV1beta1_Call struct {
	*mock.Call
}

// ResourceV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) ResourceV1beta1() *MockEcosystemClientSet_ResourceV1beta1_Call {
	return &MockEcosystemClientSet_ResourceV1beta1_Call{Call: _e.mock.On("ResourceV1beta1")}
}

func (_c *MockEcosystemClientSet_ResourceV1beta1_Call) Run(run func()) *MockEcosystemClientSet_ResourceV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_ResourceV1beta1_Call) Return(_a0 resourcev1beta1.ResourceV1beta1Interface) *MockEcosystemClientSet_ResourceV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_ResourceV1beta1_Call) RunAndReturn(run func() resourcev1beta1.ResourceV1beta1Interface) *MockEcosystemClientSet_ResourceV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) SchedulingV1() schedulingv1.SchedulingV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SchedulingV1")
	}

	var r0 schedulingv1.SchedulingV1Interface
	if rf, ok := ret.Get(0).(func() schedulingv1.SchedulingV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schedulingv1.SchedulingV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_SchedulingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1'
type MockEcosystemClientSet_SchedulingV1_Call struct {
	*mock.Call
}

// SchedulingV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) SchedulingV1() *MockEcosystemClientSet_SchedulingV1_Call {
	return &MockEcosystemClientSet_SchedulingV1_Call{Call: _e.mock.On("SchedulingV1")}
}

func (_c *MockEcosystemClientSet_SchedulingV1_Call) Run(run func()) *MockEcosystemClientSet_SchedulingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_SchedulingV1_Call) Return(_a0 schedulingv1.SchedulingV1Interface) *MockEcosystemClientSet_SchedulingV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_SchedulingV1_Call) RunAndReturn(run func() schedulingv1.SchedulingV1Interface) *MockEcosystemClientSet_SchedulingV1_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) SchedulingV1alpha1() schedulingv1alpha1.SchedulingV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SchedulingV1alpha1")
	}

	var r0 schedulingv1alpha1.SchedulingV1alpha1Interface
	if rf, ok := ret.Get(0).(func() schedulingv1alpha1.SchedulingV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schedulingv1alpha1.SchedulingV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_SchedulingV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1alpha1'
type MockEcosystemClientSet_SchedulingV1alpha1_Call struct {
	*mock.Call
}

// SchedulingV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) SchedulingV1alpha1() *MockEcosystemClientSet_SchedulingV1alpha1_Call {
	return &MockEcosystemClientSet_SchedulingV1alpha1_Call{Call: _e.mock.On("SchedulingV1alpha1")}
}

func (_c *MockEcosystemClientSet_SchedulingV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_SchedulingV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_SchedulingV1alpha1_Call) Return(_a0 schedulingv1alpha1.SchedulingV1alpha1Interface) *MockEcosystemClientSet_SchedulingV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_SchedulingV1alpha1_Call) RunAndReturn(run func() schedulingv1alpha1.SchedulingV1alpha1Interface) *MockEcosystemClientSet_SchedulingV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) SchedulingV1beta1() schedulingv1beta1.SchedulingV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SchedulingV1beta1")
	}

	var r0 schedulingv1beta1.SchedulingV1beta1Interface
	if rf, ok := ret.Get(0).(func() schedulingv1beta1.SchedulingV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schedulingv1beta1.SchedulingV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_SchedulingV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1beta1'
type MockEcosystemClientSet_SchedulingV1beta1_Call struct {
	*mock.Call
}

// SchedulingV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) SchedulingV1beta1() *MockEcosystemClientSet_SchedulingV1beta1_Call {
	return &MockEcosystemClientSet_SchedulingV1beta1_Call{Call: _e.mock.On("SchedulingV1beta1")}
}

func (_c *MockEcosystemClientSet_SchedulingV1beta1_Call) Run(run func()) *MockEcosystemClientSet_SchedulingV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_SchedulingV1beta1_Call) Return(_a0 schedulingv1beta1.SchedulingV1beta1Interface) *MockEcosystemClientSet_SchedulingV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_SchedulingV1beta1_Call) RunAndReturn(run func() schedulingv1beta1.SchedulingV1beta1Interface) *MockEcosystemClientSet_SchedulingV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) StorageV1() storagev1.StorageV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StorageV1")
	}

	var r0 storagev1.StorageV1Interface
	if rf, ok := ret.Get(0).(func() storagev1.StorageV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storagev1.StorageV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_StorageV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1'
type MockEcosystemClientSet_StorageV1_Call struct {
	*mock.Call
}

// StorageV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) StorageV1() *MockEcosystemClientSet_StorageV1_Call {
	return &MockEcosystemClientSet_StorageV1_Call{Call: _e.mock.On("StorageV1")}
}

func (_c *MockEcosystemClientSet_StorageV1_Call) Run(run func()) *MockEcosystemClientSet_StorageV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_StorageV1_Call) Return(_a0 storagev1.StorageV1Interface) *MockEcosystemClientSet_StorageV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_StorageV1_Call) RunAndReturn(run func() storagev1.StorageV1Interface) *MockEcosystemClientSet_StorageV1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) StorageV1alpha1() storagev1alpha1.StorageV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StorageV1alpha1")
	}

	var r0 storagev1alpha1.StorageV1alpha1Interface
	if rf, ok := ret.Get(0).(func() storagev1alpha1.StorageV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storagev1alpha1.StorageV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_StorageV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1alpha1'
type MockEcosystemClientSet_StorageV1alpha1_Call struct {
	*mock.Call
}

// StorageV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) StorageV1alpha1() *MockEcosystemClientSet_StorageV1alpha1_Call {
	return &MockEcosystemClientSet_StorageV1alpha1_Call{Call: _e.mock.On("StorageV1alpha1")}
}

func (_c *MockEcosystemClientSet_StorageV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_StorageV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_StorageV1alpha1_Call) Return(_a0 storagev1alpha1.StorageV1alpha1Interface) *MockEcosystemClientSet_StorageV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_StorageV1alpha1_Call) RunAndReturn(run func() storagev1alpha1.StorageV1alpha1Interface) *MockEcosystemClientSet_StorageV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1beta1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) StorageV1beta1() storagev1beta1.StorageV1beta1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StorageV1beta1")
	}

	var r0 storagev1beta1.StorageV1beta1Interface
	if rf, ok := ret.Get(0).(func() storagev1beta1.StorageV1beta1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storagev1beta1.StorageV1beta1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_StorageV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1beta1'
type MockEcosystemClientSet_StorageV1beta1_Call struct {
	*mock.Call
}

// StorageV1beta1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) StorageV1beta1() *MockEcosystemClientSet_StorageV1beta1_Call {
	return &MockEcosystemClientSet_StorageV1beta1_Call{Call: _e.mock.On("StorageV1beta1")}
}

func (_c *MockEcosystemClientSet_StorageV1beta1_Call) Run(run func()) *MockEcosystemClientSet_StorageV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_StorageV1beta1_Call) Return(_a0 storagev1beta1.StorageV1beta1Interface) *MockEcosystemClientSet_StorageV1beta1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_StorageV1beta1_Call) RunAndReturn(run func() storagev1beta1.StorageV1beta1Interface) *MockEcosystemClientSet_StorageV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// StoragemigrationV1alpha1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) StoragemigrationV1alpha1() storagemigrationv1alpha1.StoragemigrationV1alpha1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StoragemigrationV1alpha1")
	}

	var r0 storagemigrationv1alpha1.StoragemigrationV1alpha1Interface
	if rf, ok := ret.Get(0).(func() storagemigrationv1alpha1.StoragemigrationV1alpha1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storagemigrationv1alpha1.StoragemigrationV1alpha1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_StoragemigrationV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoragemigrationV1alpha1'
type MockEcosystemClientSet_StoragemigrationV1alpha1_Call struct {
	*mock.Call
}

// StoragemigrationV1alpha1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) StoragemigrationV1alpha1() *MockEcosystemClientSet_StoragemigrationV1alpha1_Call {
	return &MockEcosystemClientSet_StoragemigrationV1alpha1_Call{Call: _e.mock.On("StoragemigrationV1alpha1")}
}

func (_c *MockEcosystemClientSet_StoragemigrationV1alpha1_Call) Run(run func()) *MockEcosystemClientSet_StoragemigrationV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_StoragemigrationV1alpha1_Call) Return(_a0 storagemigrationv1alpha1.StoragemigrationV1alpha1Interface) *MockEcosystemClientSet_StoragemigrationV1alpha1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_StoragemigrationV1alpha1_Call) RunAndReturn(run func() storagemigrationv1alpha1.StoragemigrationV1alpha1Interface) *MockEcosystemClientSet_StoragemigrationV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// SupportArchiveV1 provides a mock function with no fields
func (_m *MockEcosystemClientSet) SupportArchiveV1() clientv1.SupportArchiveV1Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportArchiveV1")
	}

	var r0 clientv1.SupportArchiveV1Interface
	if rf, ok := ret.Get(0).(func() clientv1.SupportArchiveV1Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientv1.SupportArchiveV1Interface)
		}
	}

	return r0
}

// MockEcosystemClientSet_SupportArchiveV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportArchiveV1'
type MockEcosystemClientSet_SupportArchiveV1_Call struct {
	*mock.Call
}

// SupportArchiveV1 is a helper method to define mock.On call
func (_e *MockEcosystemClientSet_Expecter) SupportArchiveV1() *MockEcosystemClientSet_SupportArchiveV1_Call {
	return &MockEcosystemClientSet_SupportArchiveV1_Call{Call: _e.mock.On("SupportArchiveV1")}
}

func (_c *MockEcosystemClientSet_SupportArchiveV1_Call) Run(run func()) *MockEcosystemClientSet_SupportArchiveV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEcosystemClientSet_SupportArchiveV1_Call) Return(_a0 clientv1.SupportArchiveV1Interface) *MockEcosystemClientSet_SupportArchiveV1_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemClientSet_SupportArchiveV1_Call) RunAndReturn(run func() clientv1.SupportArchiveV1Interface) *MockEcosystemClientSet_SupportArchiveV1_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEcosystemClientSet creates a new instance of MockEcosystemClientSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEcosystemClientSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEcosystemClientSet {
	mock := &MockEcosystemClientSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
