// Code generated by mockery v2.53.3. DO NOT EDIT.

package reconciler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockArchiveCleaner is an autogenerated mock type for the archiveCleaner type
type mockArchiveCleaner struct {
	mock.Mock
}

type mockArchiveCleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockArchiveCleaner) EXPECT() *mockArchiveCleaner_Expecter {
	return &mockArchiveCleaner_Expecter{mock: &_m.Mock}
}

// Clean provides a mock function with given fields: ctx, supportArchiveName, namespace
func (_m *mockArchiveCleaner) Clean(ctx context.Context, supportArchiveName string, namespace string) error {
	ret := _m.Called(ctx, supportArchiveName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Clean")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, supportArchiveName, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockArchiveCleaner_Clean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clean'
type mockArchiveCleaner_Clean_Call struct {
	*mock.Call
}

// Clean is a helper method to define mock.On call
//   - ctx context.Context
//   - supportArchiveName string
//   - namespace string
func (_e *mockArchiveCleaner_Expecter) Clean(ctx interface{}, supportArchiveName interface{}, namespace interface{}) *mockArchiveCleaner_Clean_Call {
	return &mockArchiveCleaner_Clean_Call{Call: _e.mock.On("Clean", ctx, supportArchiveName, namespace)}
}

func (_c *mockArchiveCleaner_Clean_Call) Run(run func(ctx context.Context, supportArchiveName string, namespace string)) *mockArchiveCleaner_Clean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockArchiveCleaner_Clean_Call) Return(_a0 error) *mockArchiveCleaner_Clean_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockArchiveCleaner_Clean_Call) RunAndReturn(run func(context.Context, string, string) error) *mockArchiveCleaner_Clean_Call {
	_c.Call.Return(run)
	return _c
}

// newMockArchiveCleaner creates a new instance of mockArchiveCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockArchiveCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockArchiveCleaner {
	mock := &mockArchiveCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
