# This rule is not used by the project k8s-support-archive-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to k8s.cloudogu.com.k8s.cloudogu.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-support-archive-operator
    app.kubernetes.io/managed-by: kustomize
  name: supportarchive-viewer-role
rules:
- apiGroups:
  - k8s.cloudogu.com.k8s.cloudogu.com
  resources:
  - supportarchives
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cloudogu.com.k8s.cloudogu.com
  resources:
  - supportarchives/status
  verbs:
  - get
