// Code generated by mockery v2.53.5. DO NOT EDIT.

package collector

import (
	mock "github.com/stretchr/testify/mock"
	discovery "k8s.io/client-go/discovery"

	openapi "k8s.io/client-go/openapi"

	openapi_v2 "github.com/google/gnostic-models/openapiv2"

	rest "k8s.io/client-go/rest"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	version "k8s.io/apimachinery/pkg/version"
)

// mockDiscoveryInterface is an autogenerated mock type for the discoveryInterface type
type mockDiscoveryInterface struct {
	mock.Mock
}

type mockDiscoveryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDiscoveryInterface) EXPECT() *mockDiscoveryInterface_Expecter {
	return &mockDiscoveryInterface_Expecter{mock: &_m.Mock}
}

// OpenAPISchema provides a mock function with no fields
func (_m *mockDiscoveryInterface) OpenAPISchema() (*openapi_v2.Document, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenAPISchema")
	}

	var r0 *openapi_v2.Document
	var r1 error
	if rf, ok := ret.Get(0).(func() (*openapi_v2.Document, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *openapi_v2.Document); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi_v2.Document)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDiscoveryInterface_OpenAPISchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenAPISchema'
type mockDiscoveryInterface_OpenAPISchema_Call struct {
	*mock.Call
}

// OpenAPISchema is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) OpenAPISchema() *mockDiscoveryInterface_OpenAPISchema_Call {
	return &mockDiscoveryInterface_OpenAPISchema_Call{Call: _e.mock.On("OpenAPISchema")}
}

func (_c *mockDiscoveryInterface_OpenAPISchema_Call) Run(run func()) *mockDiscoveryInterface_OpenAPISchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_OpenAPISchema_Call) Return(_a0 *openapi_v2.Document, _a1 error) *mockDiscoveryInterface_OpenAPISchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDiscoveryInterface_OpenAPISchema_Call) RunAndReturn(run func() (*openapi_v2.Document, error)) *mockDiscoveryInterface_OpenAPISchema_Call {
	_c.Call.Return(run)
	return _c
}

// OpenAPIV3 provides a mock function with no fields
func (_m *mockDiscoveryInterface) OpenAPIV3() openapi.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenAPIV3")
	}

	var r0 openapi.Client
	if rf, ok := ret.Get(0).(func() openapi.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(openapi.Client)
		}
	}

	return r0
}

// mockDiscoveryInterface_OpenAPIV3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenAPIV3'
type mockDiscoveryInterface_OpenAPIV3_Call struct {
	*mock.Call
}

// OpenAPIV3 is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) OpenAPIV3() *mockDiscoveryInterface_OpenAPIV3_Call {
	return &mockDiscoveryInterface_OpenAPIV3_Call{Call: _e.mock.On("OpenAPIV3")}
}

func (_c *mockDiscoveryInterface_OpenAPIV3_Call) Run(run func()) *mockDiscoveryInterface_OpenAPIV3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_OpenAPIV3_Call) Return(_a0 openapi.Client) *mockDiscoveryInterface_OpenAPIV3_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDiscoveryInterface_OpenAPIV3_Call) RunAndReturn(run func() openapi.Client) *mockDiscoveryInterface_OpenAPIV3_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with no fields
func (_m *mockDiscoveryInterface) RESTClient() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// mockDiscoveryInterface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type mockDiscoveryInterface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) RESTClient() *mockDiscoveryInterface_RESTClient_Call {
	return &mockDiscoveryInterface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *mockDiscoveryInterface_RESTClient_Call) Run(run func()) *mockDiscoveryInterface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_RESTClient_Call) Return(_a0 rest.Interface) *mockDiscoveryInterface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDiscoveryInterface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *mockDiscoveryInterface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// ServerGroups provides a mock function with no fields
func (_m *mockDiscoveryInterface) ServerGroups() (*v1.APIGroupList, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerGroups")
	}

	var r0 *v1.APIGroupList
	var r1 error
	if rf, ok := ret.Get(0).(func() (*v1.APIGroupList, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *v1.APIGroupList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.APIGroupList)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDiscoveryInterface_ServerGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerGroups'
type mockDiscoveryInterface_ServerGroups_Call struct {
	*mock.Call
}

// ServerGroups is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) ServerGroups() *mockDiscoveryInterface_ServerGroups_Call {
	return &mockDiscoveryInterface_ServerGroups_Call{Call: _e.mock.On("ServerGroups")}
}

func (_c *mockDiscoveryInterface_ServerGroups_Call) Run(run func()) *mockDiscoveryInterface_ServerGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_ServerGroups_Call) Return(_a0 *v1.APIGroupList, _a1 error) *mockDiscoveryInterface_ServerGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDiscoveryInterface_ServerGroups_Call) RunAndReturn(run func() (*v1.APIGroupList, error)) *mockDiscoveryInterface_ServerGroups_Call {
	_c.Call.Return(run)
	return _c
}

// ServerGroupsAndResources provides a mock function with no fields
func (_m *mockDiscoveryInterface) ServerGroupsAndResources() ([]*v1.APIGroup, []*v1.APIResourceList, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerGroupsAndResources")
	}

	var r0 []*v1.APIGroup
	var r1 []*v1.APIResourceList
	var r2 error
	if rf, ok := ret.Get(0).(func() ([]*v1.APIGroup, []*v1.APIResourceList, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*v1.APIGroup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIGroup)
		}
	}

	if rf, ok := ret.Get(1).(func() []*v1.APIResourceList); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*v1.APIResourceList)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockDiscoveryInterface_ServerGroupsAndResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerGroupsAndResources'
type mockDiscoveryInterface_ServerGroupsAndResources_Call struct {
	*mock.Call
}

// ServerGroupsAndResources is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) ServerGroupsAndResources() *mockDiscoveryInterface_ServerGroupsAndResources_Call {
	return &mockDiscoveryInterface_ServerGroupsAndResources_Call{Call: _e.mock.On("ServerGroupsAndResources")}
}

func (_c *mockDiscoveryInterface_ServerGroupsAndResources_Call) Run(run func()) *mockDiscoveryInterface_ServerGroupsAndResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_ServerGroupsAndResources_Call) Return(_a0 []*v1.APIGroup, _a1 []*v1.APIResourceList, _a2 error) *mockDiscoveryInterface_ServerGroupsAndResources_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockDiscoveryInterface_ServerGroupsAndResources_Call) RunAndReturn(run func() ([]*v1.APIGroup, []*v1.APIResourceList, error)) *mockDiscoveryInterface_ServerGroupsAndResources_Call {
	_c.Call.Return(run)
	return _c
}

// ServerPreferredNamespacedResources provides a mock function with no fields
func (_m *mockDiscoveryInterface) ServerPreferredNamespacedResources() ([]*v1.APIResourceList, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerPreferredNamespacedResources")
	}

	var r0 []*v1.APIResourceList
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*v1.APIResourceList, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*v1.APIResourceList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIResourceList)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDiscoveryInterface_ServerPreferredNamespacedResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerPreferredNamespacedResources'
type mockDiscoveryInterface_ServerPreferredNamespacedResources_Call struct {
	*mock.Call
}

// ServerPreferredNamespacedResources is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) ServerPreferredNamespacedResources() *mockDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	return &mockDiscoveryInterface_ServerPreferredNamespacedResources_Call{Call: _e.mock.On("ServerPreferredNamespacedResources")}
}

func (_c *mockDiscoveryInterface_ServerPreferredNamespacedResources_Call) Run(run func()) *mockDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_ServerPreferredNamespacedResources_Call) Return(_a0 []*v1.APIResourceList, _a1 error) *mockDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDiscoveryInterface_ServerPreferredNamespacedResources_Call) RunAndReturn(run func() ([]*v1.APIResourceList, error)) *mockDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	_c.Call.Return(run)
	return _c
}

// ServerPreferredResources provides a mock function with no fields
func (_m *mockDiscoveryInterface) ServerPreferredResources() ([]*v1.APIResourceList, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerPreferredResources")
	}

	var r0 []*v1.APIResourceList
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*v1.APIResourceList, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*v1.APIResourceList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIResourceList)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDiscoveryInterface_ServerPreferredResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerPreferredResources'
type mockDiscoveryInterface_ServerPreferredResources_Call struct {
	*mock.Call
}

// ServerPreferredResources is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) ServerPreferredResources() *mockDiscoveryInterface_ServerPreferredResources_Call {
	return &mockDiscoveryInterface_ServerPreferredResources_Call{Call: _e.mock.On("ServerPreferredResources")}
}

func (_c *mockDiscoveryInterface_ServerPreferredResources_Call) Run(run func()) *mockDiscoveryInterface_ServerPreferredResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_ServerPreferredResources_Call) Return(_a0 []*v1.APIResourceList, _a1 error) *mockDiscoveryInterface_ServerPreferredResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDiscoveryInterface_ServerPreferredResources_Call) RunAndReturn(run func() ([]*v1.APIResourceList, error)) *mockDiscoveryInterface_ServerPreferredResources_Call {
	_c.Call.Return(run)
	return _c
}

// ServerResourcesForGroupVersion provides a mock function with given fields: groupVersion
func (_m *mockDiscoveryInterface) ServerResourcesForGroupVersion(groupVersion string) (*v1.APIResourceList, error) {
	ret := _m.Called(groupVersion)

	if len(ret) == 0 {
		panic("no return value specified for ServerResourcesForGroupVersion")
	}

	var r0 *v1.APIResourceList
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.APIResourceList, error)); ok {
		return rf(groupVersion)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.APIResourceList); ok {
		r0 = rf(groupVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.APIResourceList)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDiscoveryInterface_ServerResourcesForGroupVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerResourcesForGroupVersion'
type mockDiscoveryInterface_ServerResourcesForGroupVersion_Call struct {
	*mock.Call
}

// ServerResourcesForGroupVersion is a helper method to define mock.On call
//   - groupVersion string
func (_e *mockDiscoveryInterface_Expecter) ServerResourcesForGroupVersion(groupVersion interface{}) *mockDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	return &mockDiscoveryInterface_ServerResourcesForGroupVersion_Call{Call: _e.mock.On("ServerResourcesForGroupVersion", groupVersion)}
}

func (_c *mockDiscoveryInterface_ServerResourcesForGroupVersion_Call) Run(run func(groupVersion string)) *mockDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDiscoveryInterface_ServerResourcesForGroupVersion_Call) Return(_a0 *v1.APIResourceList, _a1 error) *mockDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDiscoveryInterface_ServerResourcesForGroupVersion_Call) RunAndReturn(run func(string) (*v1.APIResourceList, error)) *mockDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ServerVersion provides a mock function with no fields
func (_m *mockDiscoveryInterface) ServerVersion() (*version.Info, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerVersion")
	}

	var r0 *version.Info
	var r1 error
	if rf, ok := ret.Get(0).(func() (*version.Info, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *version.Info); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*version.Info)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDiscoveryInterface_ServerVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerVersion'
type mockDiscoveryInterface_ServerVersion_Call struct {
	*mock.Call
}

// ServerVersion is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) ServerVersion() *mockDiscoveryInterface_ServerVersion_Call {
	return &mockDiscoveryInterface_ServerVersion_Call{Call: _e.mock.On("ServerVersion")}
}

func (_c *mockDiscoveryInterface_ServerVersion_Call) Run(run func()) *mockDiscoveryInterface_ServerVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_ServerVersion_Call) Return(_a0 *version.Info, _a1 error) *mockDiscoveryInterface_ServerVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDiscoveryInterface_ServerVersion_Call) RunAndReturn(run func() (*version.Info, error)) *mockDiscoveryInterface_ServerVersion_Call {
	_c.Call.Return(run)
	return _c
}

// WithLegacy provides a mock function with no fields
func (_m *mockDiscoveryInterface) WithLegacy() discovery.DiscoveryInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithLegacy")
	}

	var r0 discovery.DiscoveryInterface
	if rf, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}

	return r0
}

// mockDiscoveryInterface_WithLegacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLegacy'
type mockDiscoveryInterface_WithLegacy_Call struct {
	*mock.Call
}

// WithLegacy is a helper method to define mock.On call
func (_e *mockDiscoveryInterface_Expecter) WithLegacy() *mockDiscoveryInterface_WithLegacy_Call {
	return &mockDiscoveryInterface_WithLegacy_Call{Call: _e.mock.On("WithLegacy")}
}

func (_c *mockDiscoveryInterface_WithLegacy_Call) Run(run func()) *mockDiscoveryInterface_WithLegacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDiscoveryInterface_WithLegacy_Call) Return(_a0 discovery.DiscoveryInterface) *mockDiscoveryInterface_WithLegacy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDiscoveryInterface_WithLegacy_Call) RunAndReturn(run func() discovery.DiscoveryInterface) *mockDiscoveryInterface_WithLegacy_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDiscoveryInterface creates a new instance of mockDiscoveryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDiscoveryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDiscoveryInterface {
	mock := &mockDiscoveryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
