apiVersion: v1
values:
  images:
    supportArchiveOperator: cloudogu/k8s-support-archive-operator:0.1.0
patches:
  values.yaml:
    controllerManager:
      manager:
        image:
          registry: "{{ registryFrom .images.supportArchiveOperator }}"
          repository: "{{ repositoryFrom .images.supportArchiveOperator }}"
          tag: "{{ tagFrom .images.supportArchiveOperator }}"
