global:
  networkPolicies:
    enabled: true
    denyIngress: true
  imagePullSecrets:
    - name: "ces-container-registries"
controllerManager:
  manager:
    args:
      - --metrics-bind-address=:8082
      - --health-probe-bind-address=:8081
    containerSecurityContext:
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      registry: docker.io
      repository: cloudogu/k8s-support-archive-operator
      tag: 1.0.1
    resources:
      limits:
        memory: 105M
        ephemeral-storage: 100Mi
      requests:
        cpu: 15m
        memory: 105M
        ephemeral-storage: 100Mi
  env:
    logLevel: debug
    stage: development
    supportArchiveSyncInterval: 1m
    garbageCollectionInterval: 5m
    garbageCollectionNumberToKeep: 5
    nodeInfoUsageMetricStep: 30s
    nodeInfoHardwareMetricStep: 30m
    metricsMaxSamples: 11000
    logsMaxQueryResultCount: 1500 # max is 5000
    logsMaxQueryTimeWindow: 24h # max is 720h
    logsEventSourceName: loki.source.kubernetes_events
    logGateway:
      url: "http://k8s-loki-gateway.ecosystem.svc.cluster.local"
      secretName: "k8s-loki-gateway-secret"
      usernameKey: "username"
      passwordKey: "password"
    systemStateLabelSelector: # empty selects all resources
      app: ces
    systemStateGvkExclusions:
      - group: ""
        version: v1
        kind: Secret
  imagePullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 65532
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
    - name: https
      port: 8082
      protocol: TCP
      targetPort: 8082
  type: ClusterIP
webserver:
  env:
    downloadService:
      protocol: http
      port: 8080
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsGroup: 65532
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
      ephemeral-storage: 100Mi
    limits:
      memory: 64Mi
      ephemeral-storage: 100Mi
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.28.0-alpine
  imagePullPolicy: IfNotPresent
  pvc:
    accessModes:
      - ReadWriteOnce
    requests:
      storage: 5Gi
    keepOnDelete: true
  service:
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
metrics:
  service:
    name: k8s-prometheus-prometheus
    port: 9090
    protocol: http
