controllerManager:
  manager:
    args:
      - --metrics-bind-address=:8082
      - --health-probe-bind-address=:8081
    containerSecurityContext:
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      registry: docker.io
      repository: cloudogu/k8s-support-archive-operator
      tag: 0.1.2
    resources:
      limits:
        memory: 105M
        ephemeral-storage: 100Mi # avoid resource exhaustion (sonar finding)
      requests:
        cpu: 15m
        memory: 105M
  env:
    logLevel: debug
    stage: development
  imagePullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 65532
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
    - name: https
      port: 8082
      protocol: TCP
      targetPort: 8082
  type: ClusterIP
webserver:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsGroup: 65532
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
    limits:
      memory: 64Mi
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.28.0-alpine
  imagePullPolicy: IfNotPresent
  pvc:
    accessModes:
      - ReadWriteOnce
    requests:
      storage: 1Gi
    keepOnDelete: true
  service:
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
