// Code generated by mockery v2.53.3. DO NOT EDIT.

package file

import (
	fs "io/fs"

	filesystem "github.com/cloudogu/k8s-support-archive-operator/pkg/adapter/filesystem"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockSecretFs is an autogenerated mock type for the secretFs type
type mockSecretFs struct {
	mock.Mock
}

type mockSecretFs_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSecretFs) EXPECT() *mockSecretFs_Expecter {
	return &mockSecretFs_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function with given fields: dst, src
func (_m *mockSecretFs) Copy(dst io.Writer, src io.Reader) (int64, error) {
	ret := _m.Called(dst, src)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Writer, io.Reader) (int64, error)); ok {
		return rf(dst, src)
	}
	if rf, ok := ret.Get(0).(func(io.Writer, io.Reader) int64); ok {
		r0 = rf(dst, src)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(io.Writer, io.Reader) error); ok {
		r1 = rf(dst, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretFs_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type mockSecretFs_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - dst io.Writer
//   - src io.Reader
func (_e *mockSecretFs_Expecter) Copy(dst interface{}, src interface{}) *mockSecretFs_Copy_Call {
	return &mockSecretFs_Copy_Call{Call: _e.mock.On("Copy", dst, src)}
}

func (_c *mockSecretFs_Copy_Call) Run(run func(dst io.Writer, src io.Reader)) *mockSecretFs_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(io.Reader))
	})
	return _c
}

func (_c *mockSecretFs_Copy_Call) Return(written int64, err error) *mockSecretFs_Copy_Call {
	_c.Call.Return(written, err)
	return _c
}

func (_c *mockSecretFs_Copy_Call) RunAndReturn(run func(io.Writer, io.Reader) (int64, error)) *mockSecretFs_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: name
func (_m *mockSecretFs) Create(name string) (filesystem.ClosableRWFile, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 filesystem.ClosableRWFile
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (filesystem.ClosableRWFile, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) filesystem.ClosableRWFile); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filesystem.ClosableRWFile)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretFs_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockSecretFs_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *mockSecretFs_Expecter) Create(name interface{}) *mockSecretFs_Create_Call {
	return &mockSecretFs_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *mockSecretFs_Create_Call) Run(run func(name string)) *mockSecretFs_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockSecretFs_Create_Call) Return(_a0 filesystem.ClosableRWFile, _a1 error) *mockSecretFs_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretFs_Create_Call) RunAndReturn(run func(string) (filesystem.ClosableRWFile, error)) *mockSecretFs_Create_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function with given fields: path, perm
func (_m *mockSecretFs) MkdirAll(path string, perm fs.FileMode) error {
	ret := _m.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = rf(path, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSecretFs_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type mockSecretFs_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *mockSecretFs_Expecter) MkdirAll(path interface{}, perm interface{}) *mockSecretFs_MkdirAll_Call {
	return &mockSecretFs_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *mockSecretFs_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *mockSecretFs_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.FileMode))
	})
	return _c
}

func (_c *mockSecretFs_MkdirAll_Call) Return(_a0 error) *mockSecretFs_MkdirAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSecretFs_MkdirAll_Call) RunAndReturn(run func(string, fs.FileMode) error) *mockSecretFs_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: path
func (_m *mockSecretFs) Open(path string) (filesystem.ClosableRWFile, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 filesystem.ClosableRWFile
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (filesystem.ClosableRWFile, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) filesystem.ClosableRWFile); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filesystem.ClosableRWFile)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretFs_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type mockSecretFs_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - path string
func (_e *mockSecretFs_Expecter) Open(path interface{}) *mockSecretFs_Open_Call {
	return &mockSecretFs_Open_Call{Call: _e.mock.On("Open", path)}
}

func (_c *mockSecretFs_Open_Call) Run(run func(path string)) *mockSecretFs_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockSecretFs_Open_Call) Return(_a0 filesystem.ClosableRWFile, _a1 error) *mockSecretFs_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretFs_Open_Call) RunAndReturn(run func(string) (filesystem.ClosableRWFile, error)) *mockSecretFs_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function with given fields: path, flag, perm
func (_m *mockSecretFs) OpenFile(path string, flag int, perm fs.FileMode) (filesystem.ClosableRWFile, error) {
	ret := _m.Called(path, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 filesystem.ClosableRWFile
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, fs.FileMode) (filesystem.ClosableRWFile, error)); ok {
		return rf(path, flag, perm)
	}
	if rf, ok := ret.Get(0).(func(string, int, fs.FileMode) filesystem.ClosableRWFile); ok {
		r0 = rf(path, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filesystem.ClosableRWFile)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, fs.FileMode) error); ok {
		r1 = rf(path, flag, perm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretFs_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type mockSecretFs_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - path string
//   - flag int
//   - perm fs.FileMode
func (_e *mockSecretFs_Expecter) OpenFile(path interface{}, flag interface{}, perm interface{}) *mockSecretFs_OpenFile_Call {
	return &mockSecretFs_OpenFile_Call{Call: _e.mock.On("OpenFile", path, flag, perm)}
}

func (_c *mockSecretFs_OpenFile_Call) Run(run func(path string, flag int, perm fs.FileMode)) *mockSecretFs_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *mockSecretFs_OpenFile_Call) Return(_a0 filesystem.ClosableRWFile, _a1 error) *mockSecretFs_OpenFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretFs_OpenFile_Call) RunAndReturn(run func(string, int, fs.FileMode) (filesystem.ClosableRWFile, error)) *mockSecretFs_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAll provides a mock function with given fields: r
func (_m *mockSecretFs) ReadAll(r io.Reader) ([]byte, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ReadAll")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) ([]byte, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) []byte); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretFs_ReadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAll'
type mockSecretFs_ReadAll_Call struct {
	*mock.Call
}

// ReadAll is a helper method to define mock.On call
//   - r io.Reader
func (_e *mockSecretFs_Expecter) ReadAll(r interface{}) *mockSecretFs_ReadAll_Call {
	return &mockSecretFs_ReadAll_Call{Call: _e.mock.On("ReadAll", r)}
}

func (_c *mockSecretFs_ReadAll_Call) Run(run func(r io.Reader)) *mockSecretFs_ReadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *mockSecretFs_ReadAll_Call) Return(_a0 []byte, _a1 error) *mockSecretFs_ReadAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretFs_ReadAll_Call) RunAndReturn(run func(io.Reader) ([]byte, error)) *mockSecretFs_ReadAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: name
func (_m *mockSecretFs) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretFs_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type mockSecretFs_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *mockSecretFs_Expecter) ReadDir(name interface{}) *mockSecretFs_ReadDir_Call {
	return &mockSecretFs_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *mockSecretFs_ReadDir_Call) Run(run func(name string)) *mockSecretFs_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockSecretFs_ReadDir_Call) Return(_a0 []fs.DirEntry, _a1 error) *mockSecretFs_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretFs_ReadDir_Call) RunAndReturn(run func(string) ([]fs.DirEntry, error)) *mockSecretFs_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: name
func (_m *mockSecretFs) Remove(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSecretFs_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type mockSecretFs_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *mockSecretFs_Expecter) Remove(name interface{}) *mockSecretFs_Remove_Call {
	return &mockSecretFs_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *mockSecretFs_Remove_Call) Run(run func(name string)) *mockSecretFs_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockSecretFs_Remove_Call) Return(_a0 error) *mockSecretFs_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSecretFs_Remove_Call) RunAndReturn(run func(string) error) *mockSecretFs_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function with given fields: path
func (_m *mockSecretFs) RemoveAll(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSecretFs_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type mockSecretFs_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *mockSecretFs_Expecter) RemoveAll(path interface{}) *mockSecretFs_RemoveAll_Call {
	return &mockSecretFs_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *mockSecretFs_RemoveAll_Call) Run(run func(path string)) *mockSecretFs_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockSecretFs_RemoveAll_Call) Return(_a0 error) *mockSecretFs_RemoveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSecretFs_RemoveAll_Call) RunAndReturn(run func(string) error) *mockSecretFs_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *mockSecretFs) Stat(name string) (fs.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretFs_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type mockSecretFs_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *mockSecretFs_Expecter) Stat(name interface{}) *mockSecretFs_Stat_Call {
	return &mockSecretFs_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *mockSecretFs_Stat_Call) Run(run func(name string)) *mockSecretFs_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockSecretFs_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *mockSecretFs_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretFs_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *mockSecretFs_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WalkDir provides a mock function with given fields: root, fn
func (_m *mockSecretFs) WalkDir(root string, fn fs.WalkDirFunc) error {
	ret := _m.Called(root, fn)

	if len(ret) == 0 {
		panic("no return value specified for WalkDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.WalkDirFunc) error); ok {
		r0 = rf(root, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSecretFs_WalkDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalkDir'
type mockSecretFs_WalkDir_Call struct {
	*mock.Call
}

// WalkDir is a helper method to define mock.On call
//   - root string
//   - fn fs.WalkDirFunc
func (_e *mockSecretFs_Expecter) WalkDir(root interface{}, fn interface{}) *mockSecretFs_WalkDir_Call {
	return &mockSecretFs_WalkDir_Call{Call: _e.mock.On("WalkDir", root, fn)}
}

func (_c *mockSecretFs_WalkDir_Call) Run(run func(root string, fn fs.WalkDirFunc)) *mockSecretFs_WalkDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.WalkDirFunc))
	})
	return _c
}

func (_c *mockSecretFs_WalkDir_Call) Return(_a0 error) *mockSecretFs_WalkDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSecretFs_WalkDir_Call) RunAndReturn(run func(string, fs.WalkDirFunc) error) *mockSecretFs_WalkDir_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: name, data, perm
func (_m *mockSecretFs) WriteFile(name string, data []byte, perm fs.FileMode) error {
	ret := _m.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = rf(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSecretFs_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type mockSecretFs_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm fs.FileMode
func (_e *mockSecretFs_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *mockSecretFs_WriteFile_Call {
	return &mockSecretFs_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *mockSecretFs_WriteFile_Call) Run(run func(name string, data []byte, perm fs.FileMode)) *mockSecretFs_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *mockSecretFs_WriteFile_Call) Return(_a0 error) *mockSecretFs_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSecretFs_WriteFile_Call) RunAndReturn(run func(string, []byte, fs.FileMode) error) *mockSecretFs_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSecretFs creates a new instance of mockSecretFs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSecretFs(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSecretFs {
	mock := &mockSecretFs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
