apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm.fullname" . }}-manager-role
  labels: {{ include "helm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - supportarchives
    verbs:
      - get
      - list
      - update
      - watch
      - delete
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - supportarchives/status
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups: # we need this generic list and get to read the system state.
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm.fullname" . }}-manager-rolebinding
  labels: {{ include "helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "helm.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "helm.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-manager-cluster-role
  labels: {{ include "helm.labels" . | nindent 4 }}
rules:
  - apiGroups: # we need this generic list and get to read the system state.
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" . }}-manager-clusterrolebinding
  labels: {{ include "helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "helm.fullname" . }}-manager-cluster-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "helm.fullname" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
