apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-supportarchive-editor-role
  labels:
  {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.cloudogu.com.k8s.cloudogu.com
  resources:
  - supportarchives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cloudogu.com.k8s.cloudogu.com
  resources:
  - supportarchives/status
  verbs:
  - get
