// Code generated by mockery v2.53.3. DO NOT EDIT.

package state

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockZipper is an autogenerated mock type for the zipper type
type mockZipper struct {
	mock.Mock
}

type mockZipper_Expecter struct {
	mock *mock.Mock
}

func (_m *mockZipper) EXPECT() *mockZipper_Expecter {
	return &mockZipper_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *mockZipper) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockZipper_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockZipper_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockZipper_Expecter) Close() *mockZipper_Close_Call {
	return &mockZipper_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockZipper_Close_Call) Run(run func()) *mockZipper_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockZipper_Close_Call) Return(_a0 error) *mockZipper_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockZipper_Close_Call) RunAndReturn(run func() error) *mockZipper_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: name
func (_m *mockZipper) Create(name string) (io.Writer, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 io.Writer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (io.Writer, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) io.Writer); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockZipper_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockZipper_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *mockZipper_Expecter) Create(name interface{}) *mockZipper_Create_Call {
	return &mockZipper_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *mockZipper_Create_Call) Run(run func(name string)) *mockZipper_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockZipper_Create_Call) Return(_a0 io.Writer, _a1 error) *mockZipper_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockZipper_Create_Call) RunAndReturn(run func(string) (io.Writer, error)) *mockZipper_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockZipper creates a new instance of mockZipper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockZipper(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockZipper {
	mock := &mockZipper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
